// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.DataAccessLayer;

#nullable disable

namespace Spark.DataAccessLayer.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    [Migration("20220525073242_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tblAnswers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b40c110-9d22-4911-9f82-b3730bda220f"),
                            AnswerText = "Answer 0.1",
                            QuestionId = new Guid("7eda2b79-2cb4-451d-87ad-c6ac3a99edc4")
                        },
                        new
                        {
                            Id = new Guid("ba64065b-90e6-4627-a03e-d3ac77f7ee5a"),
                            AnswerText = "Answer 0.2",
                            QuestionId = new Guid("7eda2b79-2cb4-451d-87ad-c6ac3a99edc4")
                        },
                        new
                        {
                            Id = new Guid("765feb6f-b03d-423e-ab68-0875e4d270e2"),
                            AnswerText = "Answer 0.3",
                            QuestionId = new Guid("7eda2b79-2cb4-451d-87ad-c6ac3a99edc4")
                        },
                        new
                        {
                            Id = new Guid("c58ad3c0-5778-40f0-ba93-9074beb42f01"),
                            AnswerText = "Answer 0.4",
                            QuestionId = new Guid("7eda2b79-2cb4-451d-87ad-c6ac3a99edc4")
                        },
                        new
                        {
                            Id = new Guid("3c61f4d5-8353-45e9-a2ff-ba0d48312684"),
                            AnswerText = "Answer 1.1",
                            QuestionId = new Guid("6ae14977-045a-47de-b14d-94e53e1bb972")
                        },
                        new
                        {
                            Id = new Guid("11ea9f38-f6cc-45c7-a9cc-3eccaa5098a6"),
                            AnswerText = "Answer 1.2",
                            QuestionId = new Guid("6ae14977-045a-47de-b14d-94e53e1bb972")
                        },
                        new
                        {
                            Id = new Guid("6213e469-347c-4f7c-887e-3611a01ab3ca"),
                            AnswerText = "Answer 1.3",
                            QuestionId = new Guid("6ae14977-045a-47de-b14d-94e53e1bb972")
                        },
                        new
                        {
                            Id = new Guid("9aa0b862-4d6f-4de2-9965-13e62acdd61a"),
                            AnswerText = "Answer 1.4",
                            QuestionId = new Guid("6ae14977-045a-47de-b14d-94e53e1bb972")
                        },
                        new
                        {
                            Id = new Guid("23c3bee9-00a7-478f-873a-fc120512bb9f"),
                            AnswerText = "Answer 2.1",
                            QuestionId = new Guid("79498984-2b27-477e-95a2-b0234deae719")
                        },
                        new
                        {
                            Id = new Guid("6103882f-d828-44c2-8e4e-b58da8743273"),
                            AnswerText = "Answer 2.2",
                            QuestionId = new Guid("79498984-2b27-477e-95a2-b0234deae719")
                        },
                        new
                        {
                            Id = new Guid("ca6041a9-a14b-4b61-9911-d1ba3834c0d9"),
                            AnswerText = "Answer 2.3",
                            QuestionId = new Guid("79498984-2b27-477e-95a2-b0234deae719")
                        },
                        new
                        {
                            Id = new Guid("a8951950-a289-45c8-aa36-cc4be75d3bec"),
                            AnswerText = "Answer 2.4",
                            QuestionId = new Guid("79498984-2b27-477e-95a2-b0234deae719")
                        },
                        new
                        {
                            Id = new Guid("f11ed040-71e6-4b18-a6c4-c8eef1abda5c"),
                            AnswerText = "Answer 3.1",
                            QuestionId = new Guid("bbb97530-6a14-4407-b86d-70371f5f533f")
                        },
                        new
                        {
                            Id = new Guid("b91572ba-c498-48f5-938f-0c9158d3b87d"),
                            AnswerText = "Answer 3.2",
                            QuestionId = new Guid("bbb97530-6a14-4407-b86d-70371f5f533f")
                        },
                        new
                        {
                            Id = new Guid("1f70ff82-149b-49e8-b336-911ed8622707"),
                            AnswerText = "Answer 3.3",
                            QuestionId = new Guid("bbb97530-6a14-4407-b86d-70371f5f533f")
                        },
                        new
                        {
                            Id = new Guid("23bf7b12-da84-4e9b-91b0-844acd997ede"),
                            AnswerText = "Answer 3.4",
                            QuestionId = new Guid("bbb97530-6a14-4407-b86d-70371f5f533f")
                        },
                        new
                        {
                            Id = new Guid("4785e7c3-6352-42f7-a819-0e5d53ec3c79"),
                            AnswerText = "Answer 4.1",
                            QuestionId = new Guid("eef48716-cd6b-4f86-895f-31aaef411982")
                        },
                        new
                        {
                            Id = new Guid("398850d0-2a09-48d3-9362-e2efc4fd6236"),
                            AnswerText = "Answer 4.2",
                            QuestionId = new Guid("eef48716-cd6b-4f86-895f-31aaef411982")
                        },
                        new
                        {
                            Id = new Guid("a69b9778-f961-4f8e-86f5-fc2304f6847c"),
                            AnswerText = "Answer 4.3",
                            QuestionId = new Guid("eef48716-cd6b-4f86-895f-31aaef411982")
                        },
                        new
                        {
                            Id = new Guid("b36c496f-4ebd-4d57-a54f-cbd3f070df3d"),
                            AnswerText = "Answer 4.4",
                            QuestionId = new Guid("eef48716-cd6b-4f86-895f-31aaef411982")
                        },
                        new
                        {
                            Id = new Guid("94d6d97d-438d-4f5c-b9e2-3b7ff676d7de"),
                            AnswerText = "Answer 4.5",
                            QuestionId = new Guid("eef48716-cd6b-4f86-895f-31aaef411982")
                        },
                        new
                        {
                            Id = new Guid("4c54cf72-020e-42c2-a8ae-393eb5862f5f"),
                            AnswerText = "Answer 4.6",
                            QuestionId = new Guid("eef48716-cd6b-4f86-895f-31aaef411982")
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("tblChatLog", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("User1Score")
                        .HasColumnType("int");

                    b.Property<int>("User2Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tblLike", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("tblQuestions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7eda2b79-2cb4-451d-87ad-c6ac3a99edc4"),
                            QuestionBody = "What is your favorite color?"
                        },
                        new
                        {
                            Id = new Guid("6ae14977-045a-47de-b14d-94e53e1bb972"),
                            QuestionBody = "What is your favorite animal?"
                        },
                        new
                        {
                            Id = new Guid("79498984-2b27-477e-95a2-b0234deae719"),
                            QuestionBody = "What is your favorite food?"
                        },
                        new
                        {
                            Id = new Guid("bbb97530-6a14-4407-b86d-70371f5f533f"),
                            QuestionBody = "What is your favorite sport?"
                        },
                        new
                        {
                            Id = new Guid("eef48716-cd6b-4f86-895f-31aaef411982"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("4f3832bd-5cc2-4954-9d30-8b1755c43055"),
                            QuestionBody = "What is your favorite book?"
                        },
                        new
                        {
                            Id = new Guid("3d9c3c35-b49b-42f1-8daf-50e5a9b85e49"),
                            QuestionBody = "What is your favorite TV show?"
                        },
                        new
                        {
                            Id = new Guid("bb9cfd84-9ddd-4824-aa71-1e1509ccc23f"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("a3baec88-9da7-4d91-9c19-6eb651774236"),
                            QuestionBody = "What is your favorite book?"
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Age")
                        .HasMaxLength(150)
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8a559b2-f331-4e89-9c0b-91c96b47fc29"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@iea.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "123456",
                            Phone = "05362454497",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6c37c6f1-16aa-421e-9a96-63b205fd82ed"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kaangurbuz97@gmail.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Gürbüz",
                            Name = "Kaan",
                            Password = "123456",
                            Phone = "05394643458",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("26f5c70c-43b6-46f7-8f35-e50897767947"),
                            Age = (short)43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Z.Swift@live.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Cullen",
                            Name = "Grace",
                            Password = "123456",
                            Phone = "01941-384484",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9cc170b3-c0da-4787-b66f-a23774af28f1"),
                            Age = (short)48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Angel.Nash@sky.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Bradshaw",
                            Name = "Damian",
                            Password = "123456",
                            Phone = "01900-117077",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("19ae7f5e-9dbe-44cd-a841-25aed782fd4f"),
                            Age = (short)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Haines@etsy.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Hancock",
                            Name = "Caleb",
                            Password = "123456",
                            Phone = "01151-731105",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6b393d4a-4666-4914-ab2c-f2ce9c66b3dc"),
                            Age = (short)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Evan.Shepherd@gmail.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Taylor",
                            Name = "Ella",
                            Password = "123456",
                            Phone = "01258-196011",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9688c23e-f5f0-48ec-8f1f-82826948e2dd"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jasmine.Jackson@taobao.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jackson",
                            Name = "Addison",
                            Password = "123456",
                            Phone = "01733-578524",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8a754a20-529c-4d25-9d4d-61957d8b5bb9"),
                            Age = (short)62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "R.Whitehead@yahoo.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Taylor",
                            Name = "Juan",
                            Password = "123456",
                            Phone = "01534-222569",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2a92ff2d-56dc-4488-9d00-e0e09914aead"),
                            Age = (short)57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Layla.Williams@youtube.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Chadwick",
                            Name = "Daniel",
                            Password = "123456",
                            Phone = "01224-994283",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5d5446df-8ee7-4068-a6f7-f7e148db3fad"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Lewis@cnn.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Adam",
                            Name = "Brianna",
                            Password = "123456",
                            Phone = "01035-458748",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("36544ad4-024a-48af-b912-1375cace7f19"),
                            Age = (short)52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Trinity.Jackson@baidu.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Taylor",
                            Name = "Jackson",
                            Password = "123456",
                            Phone = "01445-049575",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("beebf57c-ed3a-4f25-a58e-00a90fbf33ad"),
                            Age = (short)19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Perkins@theguardian.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Leach",
                            Name = "Daniel",
                            Password = "123456",
                            Phone = "01513-354642",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("674a9c07-19bf-488a-94da-8f4799831d85"),
                            Age = (short)47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Avery.Lord@studio1337.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thomas",
                            Name = "Chase",
                            Password = "123456",
                            Phone = "01576-765717",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1085a7a4-6151-479a-ac94-0f2b1bf316c1"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Z.Giles@lego.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Power",
                            Name = "Alexis",
                            Password = "123456",
                            Phone = "01086-027158",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("32e27011-2342-478f-9a34-2cd8e767d36d"),
                            Age = (short)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "R.Taylor@sky.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Welch",
                            Name = "Jacob",
                            Password = "123456",
                            Phone = "01559-049807",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4c15acb2-9130-4f96-8308-4eabe612fe42"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "O.Baldwin@bestbuy.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Buckley",
                            Name = "Parker",
                            Password = "123456",
                            Phone = "01553-790686",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("73fa537b-21bc-4a61-a169-dcf8be7c2166"),
                            Age = (short)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Savannah.Johnson@etsy.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Nelson",
                            Name = "James",
                            Password = "123456",
                            Phone = "01905-522977",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f90ecb5-6e2a-469b-ac83-07a1a57ccbdc"),
                            Age = (short)21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ryan.Wright@pinterest.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Nash",
                            Name = "Emma",
                            Password = "123456",
                            Phone = "01709-828101",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7aeb8959-8e27-4e35-b672-9e568d0fabcd"),
                            Age = (short)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lydia.Mcfarlane@etsy.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Leach",
                            Name = "Emily",
                            Password = "123456",
                            Phone = "01850-497064",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2276e6de-e11a-4847-a77d-a902c66fe2c2"),
                            Age = (short)29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Scott.Summers@taobao.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Blair",
                            Name = "Emma",
                            Password = "123456",
                            Phone = "01338-509815",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bfd81de4-0fe9-4efd-9795-d0ef3cc2ad17"),
                            Age = (short)46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Katherine.Summers@yelp.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mac",
                            Name = "Brooklyn",
                            Password = "123456",
                            Phone = "01509-942936",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bed577fb-cf78-4c74-8452-456565f22aeb"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Mac@youtube.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thomas",
                            Name = "Addison",
                            Password = "123456",
                            Phone = "01778-621974",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f537bdb6-392f-4111-a7e5-ae8e6c9db661"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Davies@163.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wood",
                            Name = "Zoe",
                            Password = "123456",
                            Phone = "01179-845362",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("56360f0d-7ef1-4fb2-a35e-474ee16e795c"),
                            Age = (short)64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "S.Mohamed@yahoo.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Perkins",
                            Name = "Piper",
                            Password = "123456",
                            Phone = "01617-224459",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("49162509-0de9-4638-b19f-b8633903ddaf"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "E.Mohamed@baidu.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lindsay",
                            Name = "Lucy",
                            Password = "123456",
                            Phone = "01168-525580",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ce6c2d3a-8fa5-4b16-9bd7-8652c814f10f"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Peters@globo.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thomas",
                            Name = "Zoey",
                            Password = "123456",
                            Phone = "01886-281937",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d6a351a5-2235-4355-ab2c-f910d871b80f"),
                            Age = (short)36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Boyd@microsoft.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Schofield",
                            Name = "Dominic",
                            Password = "123456",
                            Phone = "01159-452209",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("075ceb89-5c6e-49b2-996a-85db9fdaf35d"),
                            Age = (short)44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "R.Briggs@globo.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Fleming",
                            Name = "Ellie",
                            Password = "123456",
                            Phone = "01373-871442",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc7c1c88-a9a2-4c3b-bff9-e16cf5aeeff3"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Mcfarlane@stackoverflow.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Smith",
                            Name = "Liam",
                            Password = "123456",
                            Phone = "01575-101017",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cfdb7924-13be-4752-8801-c922d7c868e2"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Mcgrath@sky.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Cassidy",
                            Name = "Andrea",
                            Password = "123456",
                            Phone = "01280-912988",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("74594471-8ab3-460f-9bb6-26db98c96f29"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Thomas.Sanders@stackoverflow.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mac",
                            Name = "Mark",
                            Password = "123456",
                            Phone = "01486-083549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3c76afe0-916c-4a1d-bfd8-ccf731f26228"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "S.Thompson@microsoft.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Nash",
                            Name = "Makayla",
                            Password = "123456",
                            Phone = "01845-723547",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("69edbbdc-741a-47af-967c-a3ce25c1574c"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Morgan.Welch@ebay.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Baldwin",
                            Name = "Henry",
                            Password = "123456",
                            Phone = "01478-107085",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("03fd2ee4-fc83-4aa9-8960-80a3832a8941"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Davies@bing.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Walker",
                            Name = "Jace",
                            Password = "123456",
                            Phone = "01954-069119",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("35492d67-9277-439f-a4c3-f9159aff855c"),
                            Age = (short)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Thornton@studio1337.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Leach",
                            Name = "Madison",
                            Password = "123456",
                            Phone = "01422-357398",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9faa630f-c223-4e78-8d23-fe7abccb7068"),
                            Age = (short)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Hooper@bing.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Kenny",
                            Name = "Owen",
                            Password = "123456",
                            Phone = "01524-779386",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc7d42f3-51c3-4857-8ae5-32175f0a0089"),
                            Age = (short)43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Evans@flipkart.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Perkins",
                            Name = "Lauren",
                            Password = "123456",
                            Phone = "01151-951726",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f747f0e-ffcc-4148-b400-f19a0b76e3a3"),
                            Age = (short)23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alexis.Smith@theguardian.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thorne",
                            Name = "Makayla",
                            Password = "123456",
                            Phone = "01042-895700",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3b5318c3-5e45-4e92-8230-66e203732386"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bentley.Rossi@msdn.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Schofield",
                            Name = "Parker",
                            Password = "123456",
                            Phone = "01083-421313",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01d95066-da58-4590-b117-05b7de551aa2"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Carroll@wikipedia.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Blair",
                            Name = "Jaxon",
                            Password = "123456",
                            Phone = "01077-191377",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("65142a28-31e1-4f64-84c0-1b465b1e7999"),
                            Age = (short)27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Layla.Abbott@msdn.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "White",
                            Name = "Brandon",
                            Password = "123456",
                            Phone = "01834-311801",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("084a374c-5068-4f58-a0fa-2bb63bafb2f1"),
                            Age = (short)54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jace.Chadwick@studio1337.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mclean",
                            Name = "Andrew",
                            Password = "123456",
                            Phone = "01655-337406",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserAnswer", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "User1")
                        .WithMany("User1Chats")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User2")
                        .WithMany("User2Chats")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "LikedUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("Spark.Core.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("User1Chats");

                    b.Navigation("User2Chats");

                    b.Navigation("UserAnswers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
