// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.DataAccessLayer;

#nullable disable

namespace Spark.DataAccessLayer.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    [Migration("20220520091242_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tblAnswers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("05efd886-0f48-4af4-bb33-d950db5f1258"),
                            AnswerText = "Answer 0.1",
                            QuestionId = new Guid("fad445c2-bdd3-4550-aeb0-edcf9a5a2681")
                        },
                        new
                        {
                            Id = new Guid("d7593386-4e33-4c0a-b0f1-08212579a2d7"),
                            AnswerText = "Answer 0.2",
                            QuestionId = new Guid("fad445c2-bdd3-4550-aeb0-edcf9a5a2681")
                        },
                        new
                        {
                            Id = new Guid("74b2106c-91ec-4799-93d0-254175ad3878"),
                            AnswerText = "Answer 0.3",
                            QuestionId = new Guid("fad445c2-bdd3-4550-aeb0-edcf9a5a2681")
                        },
                        new
                        {
                            Id = new Guid("3d1494f7-e04c-411b-ac4c-e4b00f6aa6e9"),
                            AnswerText = "Answer 0.4",
                            QuestionId = new Guid("fad445c2-bdd3-4550-aeb0-edcf9a5a2681")
                        },
                        new
                        {
                            Id = new Guid("73ba4de1-2fca-41db-b070-bbf73f019be9"),
                            AnswerText = "Answer 1.1",
                            QuestionId = new Guid("5742266e-03a7-46d3-8a32-9edc7cb80c02")
                        },
                        new
                        {
                            Id = new Guid("c834e037-fb97-4654-be49-3ce2079fa526"),
                            AnswerText = "Answer 1.2",
                            QuestionId = new Guid("5742266e-03a7-46d3-8a32-9edc7cb80c02")
                        },
                        new
                        {
                            Id = new Guid("5c57a581-f295-4557-a45c-07c0dfdd51dd"),
                            AnswerText = "Answer 1.3",
                            QuestionId = new Guid("5742266e-03a7-46d3-8a32-9edc7cb80c02")
                        },
                        new
                        {
                            Id = new Guid("4e00a3ac-dfc2-4e7b-9ecf-d27f7864ff7d"),
                            AnswerText = "Answer 1.4",
                            QuestionId = new Guid("5742266e-03a7-46d3-8a32-9edc7cb80c02")
                        },
                        new
                        {
                            Id = new Guid("e3c9e688-159b-4d50-b95e-7cea90e48241"),
                            AnswerText = "Answer 2.1",
                            QuestionId = new Guid("f9116a69-328d-4d52-bd5d-39f358f9e8a1")
                        },
                        new
                        {
                            Id = new Guid("d7cd0dbe-c422-4884-b68e-67e3468c132c"),
                            AnswerText = "Answer 2.2",
                            QuestionId = new Guid("f9116a69-328d-4d52-bd5d-39f358f9e8a1")
                        },
                        new
                        {
                            Id = new Guid("69cfb74b-015f-4413-a59d-17801db27753"),
                            AnswerText = "Answer 2.3",
                            QuestionId = new Guid("f9116a69-328d-4d52-bd5d-39f358f9e8a1")
                        },
                        new
                        {
                            Id = new Guid("b504af33-e204-4d81-82ae-f37fc8b8068e"),
                            AnswerText = "Answer 2.4",
                            QuestionId = new Guid("f9116a69-328d-4d52-bd5d-39f358f9e8a1")
                        },
                        new
                        {
                            Id = new Guid("81c9883e-2f5b-4414-9d1d-de839372620a"),
                            AnswerText = "Answer 3.1",
                            QuestionId = new Guid("736edf27-261c-4e98-a848-13c2517e7dd3")
                        },
                        new
                        {
                            Id = new Guid("cd6ecdec-d197-4090-a0a5-1494eb1d8db9"),
                            AnswerText = "Answer 3.2",
                            QuestionId = new Guid("736edf27-261c-4e98-a848-13c2517e7dd3")
                        },
                        new
                        {
                            Id = new Guid("f5277697-e5cf-45b2-a29f-c779eb969ec4"),
                            AnswerText = "Answer 3.3",
                            QuestionId = new Guid("736edf27-261c-4e98-a848-13c2517e7dd3")
                        },
                        new
                        {
                            Id = new Guid("2e0de8f3-cc7b-4c1a-8e1f-aff68b525d70"),
                            AnswerText = "Answer 3.4",
                            QuestionId = new Guid("736edf27-261c-4e98-a848-13c2517e7dd3")
                        },
                        new
                        {
                            Id = new Guid("40f8fb3a-975f-4bbc-a9a0-0d6b1de92074"),
                            AnswerText = "Answer 4.1",
                            QuestionId = new Guid("5f121709-5e0c-48fc-acd5-d31d8c535b2d")
                        },
                        new
                        {
                            Id = new Guid("bfebab8a-ee7a-4b5c-a398-9a9b8ae595f3"),
                            AnswerText = "Answer 4.2",
                            QuestionId = new Guid("5f121709-5e0c-48fc-acd5-d31d8c535b2d")
                        },
                        new
                        {
                            Id = new Guid("d93043df-90db-4b94-8f7b-8a080bf37deb"),
                            AnswerText = "Answer 4.3",
                            QuestionId = new Guid("5f121709-5e0c-48fc-acd5-d31d8c535b2d")
                        },
                        new
                        {
                            Id = new Guid("9cfc4298-5e9a-44ac-bb1d-9f9cabfead5d"),
                            AnswerText = "Answer 4.4",
                            QuestionId = new Guid("5f121709-5e0c-48fc-acd5-d31d8c535b2d")
                        },
                        new
                        {
                            Id = new Guid("02a3e60e-fdb5-4896-b7ed-c30e838d14ce"),
                            AnswerText = "Answer 4.5",
                            QuestionId = new Guid("5f121709-5e0c-48fc-acd5-d31d8c535b2d")
                        },
                        new
                        {
                            Id = new Guid("6b5a42b8-aded-473b-acf3-68e9ca5a2218"),
                            AnswerText = "Answer 4.6",
                            QuestionId = new Guid("5f121709-5e0c-48fc-acd5-d31d8c535b2d")
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tblLike", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("tblQuestions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fad445c2-bdd3-4550-aeb0-edcf9a5a2681"),
                            QuestionBody = "What is your favorite color?"
                        },
                        new
                        {
                            Id = new Guid("5742266e-03a7-46d3-8a32-9edc7cb80c02"),
                            QuestionBody = "What is your favorite animal?"
                        },
                        new
                        {
                            Id = new Guid("f9116a69-328d-4d52-bd5d-39f358f9e8a1"),
                            QuestionBody = "What is your favorite food?"
                        },
                        new
                        {
                            Id = new Guid("736edf27-261c-4e98-a848-13c2517e7dd3"),
                            QuestionBody = "What is your favorite sport?"
                        },
                        new
                        {
                            Id = new Guid("5f121709-5e0c-48fc-acd5-d31d8c535b2d"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("647b3149-019b-4266-92d6-e80747b8dee1"),
                            QuestionBody = "What is your favorite book?"
                        },
                        new
                        {
                            Id = new Guid("28bbb60c-a3ee-43e8-ab06-bac089b0d611"),
                            QuestionBody = "What is your favorite TV show?"
                        },
                        new
                        {
                            Id = new Guid("9fb77ee2-7ee3-409b-a6a9-2e306eb7ea26"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("ad1f79c6-920f-4d9f-a278-d75792db6950"),
                            QuestionBody = "What is your favorite book?"
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Age")
                        .HasMaxLength(150)
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("337c7827-0d5d-44c4-bca8-da25b510e036"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@iea.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "123456",
                            Phone = "05362454497",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a7f6c440-4858-43d0-aa0a-9834a9f1428c"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kaangurbuz97@gmail.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Gürbüz",
                            Name = "Kaan",
                            Password = "123456",
                            Phone = "05394643458",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("60897502-ec62-4890-8580-692ccee544f8"),
                            Age = (short)51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Naylor@etsy.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Adam",
                            Name = "Brody",
                            Password = "123456",
                            Phone = "01692-995691",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5126492a-ee60-4381-8fa7-3d163debf933"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Hooper@bing.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Dale",
                            Name = "Samuel",
                            Password = "123456",
                            Phone = "01438-344972",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d75d7571-5741-483a-9507-9691767a560a"),
                            Age = (short)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Hilton@wikipedia.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Akhtar",
                            Name = "Claire",
                            Password = "123456",
                            Phone = "01200-840685",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("590125e8-4c75-4dbe-895c-fd3268ae1735"),
                            Age = (short)46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Carter.Power@cnn.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mann",
                            Name = "Wyatt",
                            Password = "123456",
                            Phone = "01778-177548",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("17767e0e-8e08-4ca8-8418-e57b795b2865"),
                            Age = (short)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "E.Sinclair@adamriddick.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Walker",
                            Name = "Evan",
                            Password = "123456",
                            Phone = "01579-410701",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3c80f733-6b10-4c85-8664-475b149fd7f8"),
                            Age = (short)55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Peyton.Mann@bing.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Nash",
                            Name = "Julia",
                            Password = "123456",
                            Phone = "01183-002191",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("07bc3dcf-d0c1-4fff-8c29-8aae3fbd9850"),
                            Age = (short)51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Silva@bet365.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Akhtar",
                            Name = "Aaliyah",
                            Password = "123456",
                            Phone = "01622-485052",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cad5b7a1-0fb6-4950-afb9-344e0121e6b8"),
                            Age = (short)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Walker@paypal.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mcgregor",
                            Name = "Ian",
                            Password = "123456",
                            Phone = "01442-424585",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3b6b38ab-59cf-4d80-92e5-a630743dc559"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lauren.Johnson@bing.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Schofield",
                            Name = "Julian",
                            Password = "123456",
                            Phone = "01784-885980",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6db1b939-d625-4c0f-b546-1b43538f6cfa"),
                            Age = (short)56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Andrew.Thomas@bing.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Stuart",
                            Name = "Ava",
                            Password = "123456",
                            Phone = "01064-185631",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4a955d66-15eb-4033-80eb-7637e4d4bba1"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Mann@theguardian.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mcgrath",
                            Name = "Elizabeth",
                            Password = "123456",
                            Phone = "01297-937062",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bdfd9cd2-5af7-4d01-a889-ffb8c13ce777"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jace.Wyatt@bestbuy.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Abbott",
                            Name = "Oliver",
                            Password = "123456",
                            Phone = "01232-420144",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0d5872bf-eae2-47e4-95cf-91f0c828f14f"),
                            Age = (short)49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Christopher.Jackson@sky.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Haines",
                            Name = "Adrian",
                            Password = "123456",
                            Phone = "01178-033949",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("31fa4538-9734-47ad-8dc9-043906d21b2d"),
                            Age = (short)57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Mclean@flipkart.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Obrien",
                            Name = "Nathaniel",
                            Password = "123456",
                            Phone = "01662-656874",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b5c11d2a-b1f7-458c-99db-b9269afdd2cb"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Daniel.Giles@wikia.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Carroll",
                            Name = "Easton",
                            Password = "123456",
                            Phone = "01408-525210",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1fd51401-e685-40d1-9563-7603c6db415d"),
                            Age = (short)58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Madeline.Taylor@bing.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mohamed",
                            Name = "Piper",
                            Password = "123456",
                            Phone = "01537-321443",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("759078f5-37a8-4736-b344-6dd87a06a2aa"),
                            Age = (short)51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Z.Buckley@adamriddick.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Abbott",
                            Name = "Brooklyn",
                            Password = "123456",
                            Phone = "01842-839429",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ee462f9a-2008-4021-b817-54007523c85f"),
                            Age = (short)37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Green@cnn.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wyatt",
                            Name = "Avery",
                            Password = "123456",
                            Phone = "01721-407880",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f012d7f0-cc41-48f8-ab2c-b953b5d7e105"),
                            Age = (short)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ayden.Lindsay@maplin.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Giles",
                            Name = "Tristan",
                            Password = "123456",
                            Phone = "01463-909422",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2aed8567-6003-48a6-8d5d-c63f97006665"),
                            Age = (short)45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Genesis.Jackson@pinterest.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Naylor",
                            Name = "Molly",
                            Password = "123456",
                            Phone = "01446-638256",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("47894362-4df6-4134-9cec-5fac3b55a9a7"),
                            Age = (short)48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Weaver@gmail.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Giles",
                            Name = "Annabelle",
                            Password = "123456",
                            Phone = "01940-836224",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("23444ec3-ab0a-4fb2-8c45-779818036b37"),
                            Age = (short)41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Madelyn.Lindsay@paypal.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Walker",
                            Name = "Zoey",
                            Password = "123456",
                            Phone = "01603-420888",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("da180cc2-d0e7-4cd3-9db9-bcba36fe7f6a"),
                            Age = (short)43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Hooper@arstechnica.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Leach",
                            Name = "Hannah",
                            Password = "123456",
                            Phone = "01668-455875",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("88b3e7ed-0f53-42e9-8c97-b63b21eafd06"),
                            Age = (short)41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "N.Giles@bet365.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Adam",
                            Name = "Grayson",
                            Password = "123456",
                            Phone = "01899-887445",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0968fee8-3bd3-45f5-b41d-20adb97812b9"),
                            Age = (short)21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Thorne@etsy.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Osborne",
                            Name = "Ariana",
                            Password = "123456",
                            Phone = "01657-663284",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6b04f922-5cf4-407b-a93e-113f1d69494f"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "E.Mcfarlane@bet365.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Carroll",
                            Name = "Aria",
                            Password = "123456",
                            Phone = "01363-042902",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("264f2f7a-a98f-4803-b0f3-54f5986f0e2f"),
                            Age = (short)61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Shepherd@bbc.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Riddick",
                            Name = "Zoe",
                            Password = "123456",
                            Phone = "01166-847500",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("90d90a4b-62a6-4385-9e56-0200874c673c"),
                            Age = (short)21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Naomi.Mohamed@wordpress.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lord",
                            Name = "Ian",
                            Password = "123456",
                            Phone = "01781-743209",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a882684a-8163-4775-a0db-c20bc686ef57"),
                            Age = (short)46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kylie.Brown@maplin.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lindsay",
                            Name = "Daniel",
                            Password = "123456",
                            Phone = "01797-732349",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e789dad8-cf40-4fe9-bf21-338a105d7fe9"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "S.Mann@yahoo.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lord",
                            Name = "Victoria",
                            Password = "123456",
                            Phone = "01050-447042",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0e95e556-2d29-49e7-a331-7b2ae0bc739f"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "R.Stuart@theguardian.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Dale",
                            Name = "Alexandra",
                            Password = "123456",
                            Phone = "01388-195503",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3acfd925-ed5f-49e3-8a55-f299c908e0bb"),
                            Age = (short)37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "N.Harris@cnn.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lewis",
                            Name = "Violet",
                            Password = "123456",
                            Phone = "01996-385384",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3266b206-83c2-4200-9995-7b6042905ba8"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Mcgregor@bbc.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Obrien",
                            Name = "Luis",
                            Password = "123456",
                            Phone = "01259-649919",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1776e815-6a48-4236-819f-edb95f56b03a"),
                            Age = (short)27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Whittaker@expedia.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Peters",
                            Name = "Jace",
                            Password = "123456",
                            Phone = "01388-968718",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("90ff94a3-7e46-4b5a-8996-f0109d1826a8"),
                            Age = (short)30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Mac@yahoo.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Hancock",
                            Name = "Faith",
                            Password = "123456",
                            Phone = "01406-710161",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("972e5e47-7294-44b2-b9d3-dc497d0266c2"),
                            Age = (short)61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "W.Blair@bing.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Silva",
                            Name = "Scott",
                            Password = "123456",
                            Phone = "01613-606518",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("be1a0f33-5c0d-45b6-96b2-ab8cc85c91c7"),
                            Age = (short)27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sophia.Mellor@amazon.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Akhtar",
                            Name = "Bailey",
                            Password = "123456",
                            Phone = "01017-292918",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8f24c28a-6c12-4d85-a9dd-c9913b5cc1ca"),
                            Age = (short)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Vaughan@qq.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Roberts",
                            Name = "Jasmine",
                            Password = "123456",
                            Phone = "01658-119799",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4f8cfe1b-4a59-41dd-95c4-d81a9714dd54"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Makayla.Mann@wikia.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Sinclair",
                            Name = "Bailey",
                            Password = "123456",
                            Phone = "01988-195762",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("139f3be0-574f-4eaf-afe8-f3a94e3f8fd8"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "John.Power@maplin.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Sanders",
                            Name = "Annabelle",
                            Password = "123456",
                            Phone = "01025-418820",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserAnswer", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "LikedUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("Spark.Core.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("UserAnswers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
