// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.DataAccessLayer;

#nullable disable

namespace Spark.DataAccessLayer.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    [Migration("20220517140442_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tblAnswers", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tblLike", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("tblQuestions", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Age")
                        .HasMaxLength(150)
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f2ce7c1-b5c7-4c86-b4d4-b68e2bc75cab"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@iea.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "123456",
                            Phone = "05362454497",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("89c23e54-ba13-4c2f-813d-51d0ccaf549b"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kaangurbuz97@gmail.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Gürbüz",
                            Name = "Kaan",
                            Password = "123456",
                            Phone = "05394643458",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30307393-cda5-4f90-93dc-c61c0cd80e05"),
                            Age = (short)45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alexandra.Wyatt@stackoverflow.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Harris",
                            Name = "Julian",
                            Password = "123456",
                            Phone = "01745-589943",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ef6f055d-4fcd-480a-b479-e23b2290534c"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Samantha.Thornton@microsoft.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Welch",
                            Name = "Connor",
                            Password = "123456",
                            Phone = "01406-496343",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8954f994-d5f5-4489-810b-38f64b00f990"),
                            Age = (short)23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hannah.Whittaker@stackoverflow.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Rossi",
                            Name = "Alexis",
                            Password = "123456",
                            Phone = "01925-536470",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3e896de8-e49a-4449-a155-f59e170441ae"),
                            Age = (short)52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Khloe.White@wikipedia.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Naylor",
                            Name = "Tyler",
                            Password = "123456",
                            Phone = "01768-123554",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fe505e7f-6811-44cd-b691-a0bf1710915e"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Melanie.Savage@wikia.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Whittaker",
                            Name = "Sophie",
                            Password = "123456",
                            Phone = "01438-018488",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("347415f3-4b41-494f-a186-2697caaf6a30"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hannah.Power@microsoft.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Smith",
                            Name = "Carlos",
                            Password = "123456",
                            Phone = "01184-603182",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("441803c1-0a5d-47ca-a7c2-dc7b1d0bbafc"),
                            Age = (short)64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Wright@ebay.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Burrows",
                            Name = "Isaiah",
                            Password = "123456",
                            Phone = "01934-076842",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2217ebbc-c1db-4b4c-abe2-f696ba4b07e9"),
                            Age = (short)63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Paul.Whittaker@paypal.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Seymour",
                            Name = "Mackenzie",
                            Password = "123456",
                            Phone = "01883-106232",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cc9695af-c611-4a22-bf32-ab1a8b6f6186"),
                            Age = (short)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "N.Johnson@wikia.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Walters",
                            Name = "Alexis",
                            Password = "123456",
                            Phone = "01870-299437",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("154c5ed7-08ec-4a8b-ac44-1c13a6a1dc62"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Sanders@techcrunch.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Hooper",
                            Name = "Landon",
                            Password = "123456",
                            Phone = "01289-404046",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("242c3e8c-93a5-4e55-a463-4ea7b48c7647"),
                            Age = (short)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "N.Wilson@yahoo.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thompson",
                            Name = "Matthew",
                            Password = "123456",
                            Phone = "01859-063227",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("02c54e10-d31f-42c3-aeca-27b7e7dee195"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Abbott@lego.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Harris",
                            Name = "Jason",
                            Password = "123456",
                            Phone = "01468-491255",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("068b5a92-63cd-4d8b-83fe-f46cd0a2d1d7"),
                            Age = (short)40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aiden.Wyatt@bestbuy.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Davies",
                            Name = "Ellie",
                            Password = "123456",
                            Phone = "01916-293345",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c034a690-70dd-4c14-8a6f-ebf7b66ade81"),
                            Age = (short)22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Noah.Evans@paypal.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Shepherd",
                            Name = "Luis",
                            Password = "123456",
                            Phone = "01805-314536",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e463e88c-d02b-422d-a9db-77cab551f110"),
                            Age = (short)31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brody.Walker@expedia.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Davies",
                            Name = "Jeremiah",
                            Password = "123456",
                            Phone = "01227-946726",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4047bef2-0e39-4916-8032-6eba0a1bafd6"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "D.Green@paypal.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wright",
                            Name = "Molly",
                            Password = "123456",
                            Phone = "01978-453353",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("04827000-da8e-4983-bf69-511aee5eda28"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Mohamed@yahoo.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Davies",
                            Name = "Aubrey",
                            Password = "123456",
                            Phone = "01915-730836",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("128c08eb-cf81-4759-bdbd-cf8f791fc6b8"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Mcgrath@maplin.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Osborne",
                            Name = "Elijah",
                            Password = "123456",
                            Phone = "01337-326357",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a2b5a808-2c57-41ef-b1af-af7de29af070"),
                            Age = (short)33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kennedy.Davies@deviantart.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Briggs",
                            Name = "Nicholas",
                            Password = "123456",
                            Phone = "01525-516059",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4a3e85e8-c004-4827-b1f7-40a1589f8bdc"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "I.Giles@ebay.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Kenny",
                            Name = "Joseph",
                            Password = "123456",
                            Phone = "01560-717975",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("956b86c3-1bc8-4660-a537-d2f221256ddb"),
                            Age = (short)44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hailey.Harris@microsoft.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Hilton",
                            Name = "Bentley",
                            Password = "123456",
                            Phone = "01231-856453",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a3c7405b-7c66-40b4-9c0b-681eba8b982c"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Davies@adamriddick.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Whittaker",
                            Name = "Melanie",
                            Password = "123456",
                            Phone = "01615-408052",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b2cc4246-f035-40b8-bc83-d7df899b8549"),
                            Age = (short)19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aaron.Peters@studio1337.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Taylor",
                            Name = "Chloe",
                            Password = "123456",
                            Phone = "01206-538844",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2e504fff-9a7f-4961-9cf5-c078d06b7cc8"),
                            Age = (short)37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Claire.Power@microsoft.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Abbott",
                            Name = "Daniel",
                            Password = "123456",
                            Phone = "01508-857626",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc993459-168c-40b2-8a39-302be5132be5"),
                            Age = (short)58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "R.Wyatt@ask.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Cassidy",
                            Name = "Kylie",
                            Password = "123456",
                            Phone = "01932-123820",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e7fa2bb8-fc04-41d5-a5a6-d200fe3eaabf"),
                            Age = (short)57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Summers@bbc.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Haines",
                            Name = "Maya",
                            Password = "123456",
                            Phone = "01820-247582",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f6d47b86-2814-43e8-88f8-f6ac276c8881"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aiden.Akhtar@arstechnica.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Harris",
                            Name = "Elijah",
                            Password = "123456",
                            Phone = "01247-421562",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ddeaccf5-dea7-4644-9f4f-daac14e72b63"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Piper.Nash@deviantart.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thompson",
                            Name = "Nevaeh",
                            Password = "123456",
                            Phone = "01688-437045",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad8bd1af-60a5-4a65-9785-76d04b6f1911"),
                            Age = (short)31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Buckley@pinterest.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thomas",
                            Name = "Khloe",
                            Password = "123456",
                            Phone = "01826-885125",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("98cd6ea1-6175-436e-afb8-6d2d8b6a41d7"),
                            Age = (short)46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.White@pinterest.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Buckley",
                            Name = "Peyton",
                            Password = "123456",
                            Phone = "01883-944999",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("881e8867-fa27-4872-844c-4d4353f65b3b"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Swift@msdn.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Carroll",
                            Name = "Evelyn",
                            Password = "123456",
                            Phone = "01602-059644",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9360a155-1880-4a11-b3ea-d35e4e8f17be"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Arianna.Cassidy@arstechnica.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jackson",
                            Name = "Lauren",
                            Password = "123456",
                            Phone = "01998-917985",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cdfa0dbf-580e-4a29-a146-3600426b22d9"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Stuart@sky.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lindsay",
                            Name = "Brianna",
                            Password = "123456",
                            Phone = "01297-430130",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("388ab130-196f-4412-acd0-efe270f4ed7d"),
                            Age = (short)50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Michael.Nash@arstechnica.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Schofield",
                            Name = "Jason",
                            Password = "123456",
                            Phone = "01802-396118",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2f9f90e1-9f80-4b5a-952c-1b50c3487410"),
                            Age = (short)53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Peyton.Sanders@expedia.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Obrien",
                            Name = "Damian",
                            Password = "123456",
                            Phone = "01175-682114",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e307c70b-8026-4191-b9be-7f465eb4e541"),
                            Age = (short)23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Christopher.Weaver@globo.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Sanders",
                            Name = "Eva",
                            Password = "123456",
                            Phone = "01611-261454",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5f6710e6-64cd-4ab8-a254-50ecbdbd0c37"),
                            Age = (short)23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Owen.Jones@expedia.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Perkins",
                            Name = "Dylan",
                            Password = "123456",
                            Phone = "01207-578913",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("74f7da53-a727-465e-a7c5-d517e5fc195f"),
                            Age = (short)43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Johnson@wikipedia.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mcgrath",
                            Name = "Brayden",
                            Password = "123456",
                            Phone = "01797-217784",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d211e99e-be26-4690-8db2-be9ba53adbf4"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adam.Naylor@bet365.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Vaughan",
                            Name = "John",
                            Password = "123456",
                            Phone = "01108-555312",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4575210c-c311-40ce-8057-e15a93712065"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Mcfarlane@wikia.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Akhtar",
                            Name = "Owen",
                            Password = "123456",
                            Phone = "01057-302785",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserAnswer", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "LikedUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("Spark.Core.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("UserAnswers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
