// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.DataAccessLayer;

#nullable disable

namespace Spark.DataAccessLayer.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    [Migration("20220516143723_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tblAnswers", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tblLike", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("tblQuestions", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Age")
                        .HasMaxLength(150)
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3e50a24-f539-43d7-bad8-b050d13729ce"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@iea.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDelete = false,
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "123456",
                            Phone = "05362454497",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("99736e86-f22b-4b62-b658-7d69dd52e989"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kaangurbuz97@gmail.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDelete = false,
                            LastName = "Gürbüz",
                            Name = "Kaan",
                            Password = "123456",
                            Phone = "05394643458",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4f371877-3d4f-4c3b-8838-21f491e2d88e"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Christian.Jackson@ask.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Whittaker",
                            Name = "Aiden",
                            Password = "123456",
                            Phone = "01721-542695",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6e117ba4-5f7f-459c-b96c-5bfdf61c85b0"),
                            Age = (short)49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jocelyn.Nash@deviantart.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Hilton",
                            Name = "Chase",
                            Password = "123456",
                            Phone = "01964-867379",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e46d086a-1b7a-4995-92cf-a24ed2e1245d"),
                            Age = (short)30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Z.Kenny@yahoo.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Bradshaw",
                            Name = "Carter",
                            Password = "123456",
                            Phone = "01580-970979",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0f2ef133-36b3-4995-b3bc-abb5af5843e4"),
                            Age = (short)55,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "O.Wood@wordpress.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Whittaker",
                            Name = "Gianna",
                            Password = "123456",
                            Phone = "01002-550248",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c8d1b9c-76af-4e7a-a925-daddfd51b420"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brandon.Adam@bbc.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Wilson",
                            Name = "Nathan",
                            Password = "123456",
                            Phone = "01974-355752",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("386a7920-e998-4b48-9998-5033e7615839"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nevaeh.Power@expedia.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Taylor",
                            Name = "Serenity",
                            Password = "123456",
                            Phone = "01144-775715",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f9a8e97f-4de2-462c-9170-2f1764b27d6b"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Andrew.Akhtar@paypal.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Wright",
                            Name = "Samantha",
                            Password = "123456",
                            Phone = "01639-232613",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ff6c6a76-36ec-4e91-8a7e-309837a2d689"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Carlos.Coles@bing.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Riddick",
                            Name = "Scott",
                            Password = "123456",
                            Phone = "01763-347544",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f680d8d1-4de7-4a59-9a4d-05881b9e675a"),
                            Age = (short)64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "I.Taylor@taobao.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Evans",
                            Name = "Arianna",
                            Password = "123456",
                            Phone = "01125-830038",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e9be112d-0645-408f-8c7a-cdc19ff0c904"),
                            Age = (short)45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Vaughan@globo.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Seymour",
                            Name = "Brianna",
                            Password = "123456",
                            Phone = "01049-156843",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6a36e0b3-4595-4a75-a909-b9e0025d4cb3"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Paul.Kenny@yelp.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Dale",
                            Name = "Hannah",
                            Password = "123456",
                            Phone = "01739-038510",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("aada3d54-a942-4acc-84bc-403c3eb62515"),
                            Age = (short)63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hailey.Seymour@yahoo.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Haines",
                            Name = "Paul",
                            Password = "123456",
                            Phone = "01373-010780",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("53665135-7cf0-4969-ab5a-18fc280774dd"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Blair@wikipedia.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Barlow",
                            Name = "David",
                            Password = "123456",
                            Phone = "01567-488974",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2d825efc-0a26-460c-8803-79fbf5d9dea8"),
                            Age = (short)41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Dale@sky.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Mcgregor",
                            Name = "Grace",
                            Password = "123456",
                            Phone = "01670-406270",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f193e6de-aa26-4bbf-baef-80794aafd471"),
                            Age = (short)56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "I.Sinclair@amazon.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Perkins",
                            Name = "Zoe",
                            Password = "123456",
                            Phone = "01348-319732",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f236db47-c829-4a70-8edf-32e33f2a2dce"),
                            Age = (short)58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Gabriel.Mohamed@etsy.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Mann",
                            Name = "Ellie",
                            Password = "123456",
                            Phone = "01567-109778",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("49ef73bb-8937-439b-a197-b43353158d02"),
                            Age = (short)61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Smith@amazon.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Little",
                            Name = "Aiden",
                            Password = "123456",
                            Phone = "01600-960113",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d391342d-2038-47d2-b80f-7f44aacf8d6c"),
                            Age = (short)61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Dale@linkedin.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Thorne",
                            Name = "Levi",
                            Password = "123456",
                            Phone = "01777-051367",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bb8a9fd7-d933-47b7-8776-a99415b92b1e"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nicholas.Thorne@qq.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Sanders",
                            Name = "Kimberly",
                            Password = "123456",
                            Phone = "01228-370251",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c76ee95e-c59c-44e1-b949-7031e7fb5def"),
                            Age = (short)30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Jackson@maplin.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Mann",
                            Name = "Noah",
                            Password = "123456",
                            Phone = "01311-228702",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("20e5eb00-8894-4eb5-84b2-a464a7ab926c"),
                            Age = (short)43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "William.Weaver@maplin.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Thorne",
                            Name = "Nolan",
                            Password = "123456",
                            Phone = "01755-135382",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("670d3855-3cb8-4ae7-a56e-39eb3ea7eaeb"),
                            Age = (short)52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Leah.Lewis@yahoo.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Whitehouse",
                            Name = "Julian",
                            Password = "123456",
                            Phone = "01333-762820",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5fe44042-0ea9-4ec3-a04f-bc80dd37c86d"),
                            Age = (short)29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Madelyn.Davies@flipkart.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Lord",
                            Name = "Adrian",
                            Password = "123456",
                            Phone = "01834-804748",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b042e33b-f45f-43df-a197-8688e74f4ef0"),
                            Age = (short)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Wright@theguardian.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Perkins",
                            Name = "Genesis",
                            Password = "123456",
                            Phone = "01236-392528",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f3060891-47da-4c46-862d-4f324ceb7f83"),
                            Age = (short)47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Camila.Harris@bet365.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Joyce",
                            Name = "Chloe",
                            Password = "123456",
                            Phone = "01078-439692",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8283c163-8d0f-45ad-88be-3a16673942ab"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Paul.Seymour@live.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Giles",
                            Name = "Blake",
                            Password = "123456",
                            Phone = "01676-401177",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c63ee999-8702-4f06-905a-8cf3a8e063ad"),
                            Age = (short)50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kimberly.Lewis@microsoft.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Coles",
                            Name = "Khloe",
                            Password = "123456",
                            Phone = "01867-762405",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("df32c9ad-1a11-48ba-9de9-3c6bb7b8e73b"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aubree.Boyd@microsoft.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Little",
                            Name = "Joseph",
                            Password = "123456",
                            Phone = "01773-467668",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("68b2dd24-2035-401e-8c25-7c95ba057ecd"),
                            Age = (short)33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Burrows@lego.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Evans",
                            Name = "Chase",
                            Password = "123456",
                            Phone = "01177-625073",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fbdcc012-4f66-4352-b4b2-b233fd36f78c"),
                            Age = (short)54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "V.Jackson@live.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Schofield",
                            Name = "Gabriella",
                            Password = "123456",
                            Phone = "01629-866218",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dd8765d8-fa0f-4122-8b2b-6fec528b42b0"),
                            Age = (short)30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Weaver@google.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Walters",
                            Name = "Zoe",
                            Password = "123456",
                            Phone = "01491-739607",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ca136757-7295-4ac0-9e86-f2d8c82d8175"),
                            Age = (short)32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Zachary.Davies@adamriddick.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Wyatt",
                            Name = "Alex",
                            Password = "123456",
                            Phone = "01988-863312",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8ad51c00-6963-4a9d-be03-515904d45972"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "N.Wilson@sohu.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Schofield",
                            Name = "Lucas",
                            Password = "123456",
                            Phone = "01881-250298",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00c97c80-4923-47e4-b6ea-398eccac6609"),
                            Age = (short)31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Owen.Osborne@adamriddick.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Wyatt",
                            Name = "Henry",
                            Password = "123456",
                            Phone = "01946-888801",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55f115f6-6964-4ce7-b330-9855d94b15f3"),
                            Age = (short)47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jason.Silva@taobao.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Abbott",
                            Name = "Madelyn",
                            Password = "123456",
                            Phone = "01971-768269",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fb4aee7d-72c9-43ac-b29b-8033e16d03be"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Charlotte.Wood@bet365.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Mcgregor",
                            Name = "Reagan",
                            Password = "123456",
                            Phone = "01186-686136",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1a16e47b-0f8b-4ec2-a996-b5946403f9aa"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Coles@theguardian.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Abbott",
                            Name = "Evelyn",
                            Password = "123456",
                            Phone = "01353-566700",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("409fd00a-3483-443c-a55b-e7374730cab1"),
                            Age = (short)64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lillian.Shepherd@microsoft.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Haines",
                            Name = "Jose",
                            Password = "123456",
                            Phone = "01105-830848",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("701c1a2c-a92b-4f37-ab8d-f7fcd1794972"),
                            Age = (short)50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mia.Burrows@adamriddick.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Wright",
                            Name = "Carlos",
                            Password = "123456",
                            Phone = "01026-831385",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad9d700f-58db-4b29-806d-b943a1eb2e1c"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jocelyn.Fleming@bing.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDelete = false,
                            LastName = "Green",
                            Name = "Bailey",
                            Password = "123456",
                            Phone = "01988-747320",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserAnswer", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "LikedUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("Spark.Core.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("UserAnswers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
