// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.DataAccessLayer;

#nullable disable

namespace Spark.DataAccessLayer.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    partial class SparkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tblAnswers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a1709d-3527-4134-990d-7333b451878d"),
                            AnswerText = "Answer 0.1",
                            QuestionId = new Guid("b6222443-5296-4699-ae39-b9ff8270b96e")
                        },
                        new
                        {
                            Id = new Guid("ce4490d6-f803-4501-a36c-d4b305c6e51d"),
                            AnswerText = "Answer 0.2",
                            QuestionId = new Guid("b6222443-5296-4699-ae39-b9ff8270b96e")
                        },
                        new
                        {
                            Id = new Guid("fbcfd830-903b-40a2-8aa2-92c4537723e1"),
                            AnswerText = "Answer 0.3",
                            QuestionId = new Guid("b6222443-5296-4699-ae39-b9ff8270b96e")
                        },
                        new
                        {
                            Id = new Guid("d5cb4d38-8b5f-4940-b3ec-b4c0034206cc"),
                            AnswerText = "Answer 0.4",
                            QuestionId = new Guid("b6222443-5296-4699-ae39-b9ff8270b96e")
                        },
                        new
                        {
                            Id = new Guid("191f53a3-3715-492e-84f0-b5f629e8c7a3"),
                            AnswerText = "Answer 1.1",
                            QuestionId = new Guid("7e180b35-4b90-41b4-8250-f39270a648e2")
                        },
                        new
                        {
                            Id = new Guid("07dfd529-f4d8-4bf6-9045-b43b053deb32"),
                            AnswerText = "Answer 1.2",
                            QuestionId = new Guid("7e180b35-4b90-41b4-8250-f39270a648e2")
                        },
                        new
                        {
                            Id = new Guid("2753da9c-06e6-495e-97f0-6832ea3cd79b"),
                            AnswerText = "Answer 1.3",
                            QuestionId = new Guid("7e180b35-4b90-41b4-8250-f39270a648e2")
                        },
                        new
                        {
                            Id = new Guid("91116e78-8fa1-4d25-8d2d-1d062b0ba07c"),
                            AnswerText = "Answer 1.4",
                            QuestionId = new Guid("7e180b35-4b90-41b4-8250-f39270a648e2")
                        },
                        new
                        {
                            Id = new Guid("df56b7cf-7ce8-4820-99cf-3b78f5baa262"),
                            AnswerText = "Answer 2.1",
                            QuestionId = new Guid("f29c6a5d-c417-4a2c-9562-dec2af3f461b")
                        },
                        new
                        {
                            Id = new Guid("d45e560a-3265-4462-bea5-8b1b7127c972"),
                            AnswerText = "Answer 2.2",
                            QuestionId = new Guid("f29c6a5d-c417-4a2c-9562-dec2af3f461b")
                        },
                        new
                        {
                            Id = new Guid("868c8dc0-8614-415f-8f21-50e393d068ff"),
                            AnswerText = "Answer 2.3",
                            QuestionId = new Guid("f29c6a5d-c417-4a2c-9562-dec2af3f461b")
                        },
                        new
                        {
                            Id = new Guid("114a4d61-8c68-4f3e-b06d-4f110269a4fe"),
                            AnswerText = "Answer 2.4",
                            QuestionId = new Guid("f29c6a5d-c417-4a2c-9562-dec2af3f461b")
                        },
                        new
                        {
                            Id = new Guid("bd5dec57-7d87-49bd-8f33-86a4a5916c97"),
                            AnswerText = "Answer 3.1",
                            QuestionId = new Guid("edeccd3d-90fb-4d78-b7fd-fcfa341eff18")
                        },
                        new
                        {
                            Id = new Guid("f84d507a-bbac-4e76-b3d7-641d64b1cc09"),
                            AnswerText = "Answer 3.2",
                            QuestionId = new Guid("edeccd3d-90fb-4d78-b7fd-fcfa341eff18")
                        },
                        new
                        {
                            Id = new Guid("f2b2de69-18f1-459d-9e2e-7eb5d91c234f"),
                            AnswerText = "Answer 3.3",
                            QuestionId = new Guid("edeccd3d-90fb-4d78-b7fd-fcfa341eff18")
                        },
                        new
                        {
                            Id = new Guid("98b6a762-1cf0-4ecb-858e-4e63ad1da857"),
                            AnswerText = "Answer 3.4",
                            QuestionId = new Guid("edeccd3d-90fb-4d78-b7fd-fcfa341eff18")
                        },
                        new
                        {
                            Id = new Guid("0a492e4d-349a-4eb3-983c-51a2299ee72c"),
                            AnswerText = "Answer 4.1",
                            QuestionId = new Guid("b5a88634-d209-41cb-9aa6-466290b5d2e4")
                        },
                        new
                        {
                            Id = new Guid("9fec29ad-1ef4-4344-929a-e2bf4f177372"),
                            AnswerText = "Answer 4.2",
                            QuestionId = new Guid("b5a88634-d209-41cb-9aa6-466290b5d2e4")
                        },
                        new
                        {
                            Id = new Guid("1f5b3a24-6bfd-4779-80b4-b3bd368211ed"),
                            AnswerText = "Answer 4.3",
                            QuestionId = new Guid("b5a88634-d209-41cb-9aa6-466290b5d2e4")
                        },
                        new
                        {
                            Id = new Guid("0145dd3c-575a-40d6-a39d-a16a9eba290f"),
                            AnswerText = "Answer 4.4",
                            QuestionId = new Guid("b5a88634-d209-41cb-9aa6-466290b5d2e4")
                        },
                        new
                        {
                            Id = new Guid("8ef41893-60a0-43ea-adb5-4db6c095d9af"),
                            AnswerText = "Answer 4.5",
                            QuestionId = new Guid("b5a88634-d209-41cb-9aa6-466290b5d2e4")
                        },
                        new
                        {
                            Id = new Guid("c7367061-ce34-499d-b3aa-7bbb57635339"),
                            AnswerText = "Answer 4.6",
                            QuestionId = new Guid("b5a88634-d209-41cb-9aa6-466290b5d2e4")
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("tblChatLog", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("User1Score")
                        .HasColumnType("int");

                    b.Property<int>("User2Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tblLike", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("tblQuestions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6222443-5296-4699-ae39-b9ff8270b96e"),
                            QuestionBody = "What is your favorite color?"
                        },
                        new
                        {
                            Id = new Guid("7e180b35-4b90-41b4-8250-f39270a648e2"),
                            QuestionBody = "What is your favorite animal?"
                        },
                        new
                        {
                            Id = new Guid("f29c6a5d-c417-4a2c-9562-dec2af3f461b"),
                            QuestionBody = "What is your favorite food?"
                        },
                        new
                        {
                            Id = new Guid("edeccd3d-90fb-4d78-b7fd-fcfa341eff18"),
                            QuestionBody = "What is your favorite sport?"
                        },
                        new
                        {
                            Id = new Guid("b5a88634-d209-41cb-9aa6-466290b5d2e4"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("f142e944-f396-4cc0-8566-42588ee8fc00"),
                            QuestionBody = "What is your favorite book?"
                        },
                        new
                        {
                            Id = new Guid("87ea7ab2-e69a-4227-afbd-c71bf7bdc143"),
                            QuestionBody = "What is your favorite TV show?"
                        },
                        new
                        {
                            Id = new Guid("fcca64fb-15bb-4981-b76f-2b12f48b968f"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("54145deb-76bf-4908-ae1e-467afa6c22a4"),
                            QuestionBody = "What is your favorite book?"
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Age")
                        .HasMaxLength(150)
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("07272899-7597-4a45-a73d-c84f0a301bff"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@iea.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            Name = "Admin",
                            Password = "123456",
                            Phone = "05362454497",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f293b8e4-ff8a-4126-b9c0-a60d8767efd3"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kaangurbuz97@gmail.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Gürbüz",
                            Name = "Kaan",
                            Password = "123456",
                            Phone = "05394643458",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e00a426c-8535-4512-a301-733c228fe167"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Juan.Mcgregor@linkedin.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Welch",
                            Name = "Harper",
                            Password = "123456",
                            Phone = "01623-298344",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b706b5ad-ee11-41c4-ac16-c9b7d66de3ed"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Baldwin@taobao.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Cullen",
                            Name = "Nolan",
                            Password = "123456",
                            Phone = "01018-414246",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9e0576ae-bef3-4bd6-b399-3fa7841b34b7"),
                            Age = (short)48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Thornton@youtube.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Osborne",
                            Name = "Isaac",
                            Password = "123456",
                            Phone = "01269-968969",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("15fde5fc-1667-457d-8d16-f79b0a3e7279"),
                            Age = (short)64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Faith.Harris@qq.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Walker",
                            Name = "Scott",
                            Password = "123456",
                            Phone = "01267-226284",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("611660f6-70a1-4208-a7af-281c2d08f78c"),
                            Age = (short)45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Mclean@deviantart.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lord",
                            Name = "Kylie",
                            Password = "123456",
                            Phone = "01255-413564",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f9b6aee7-06c0-4b7b-a2f2-55a34d92e6ac"),
                            Age = (short)36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Stella.Swift@theguardian.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thornton",
                            Name = "Tyler",
                            Password = "123456",
                            Phone = "01162-725662",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8e97b84c-d6f3-41bf-bcd0-2a472766ed98"),
                            Age = (short)19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Lindsay@pinterest.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Johnson",
                            Name = "Blake",
                            Password = "123456",
                            Phone = "01091-264980",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1ab0e397-92ce-4ac9-b1d1-e36c84977dda"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Skylar.Wilson@stackoverflow.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Robinson",
                            Name = "Nolan",
                            Password = "123456",
                            Phone = "01100-206174",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ec39c5dc-e97d-4591-8f98-4cba41579dc1"),
                            Age = (short)28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Caroline.Welch@stackoverflow.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Adam",
                            Name = "Allison",
                            Password = "123456",
                            Phone = "01932-587125",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0a6e136d-a9ca-42d2-8c09-dcc472d1bf3c"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Z.Mellor@wikia.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Kenny",
                            Name = "Riley",
                            Password = "123456",
                            Phone = "01526-404599",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d93cb362-fdb0-4b47-9949-839edde5a4d6"),
                            Age = (short)50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Faith.Seymour@globo.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Watson",
                            Name = "Layla",
                            Password = "123456",
                            Phone = "01577-690193",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0797d602-d9f4-4726-9989-f8bcfbb0e361"),
                            Age = (short)44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "William.Mac@etsy.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Silva",
                            Name = "Lauren",
                            Password = "123456",
                            Phone = "01946-807445",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0f2983f3-3fc9-441f-b8c9-c38ce9d3a949"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Chloe.Wilson@flipkart.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wilson",
                            Name = "Evelyn",
                            Password = "123456",
                            Phone = "01262-142766",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e53ff7e4-b7bc-4d2e-90e9-614d9b75bb1f"),
                            Age = (short)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lily.Kenny@live.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wright",
                            Name = "Jaxon",
                            Password = "123456",
                            Phone = "01952-517532",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1190ca82-e738-4915-9276-a38f79491fcf"),
                            Age = (short)22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Hilton@theguardian.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Weaver",
                            Name = "Mia",
                            Password = "123456",
                            Phone = "01881-955313",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b468cdc2-0aef-4ae3-9236-e0e3749ebd91"),
                            Age = (short)23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adrian.Jackson@qq.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Walters",
                            Name = "Morgan",
                            Password = "123456",
                            Phone = "01960-065326",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5f39aaee-3fc8-4bab-9f49-bbb401cd3f13"),
                            Age = (short)46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Chadwick@live.org.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Obrien",
                            Name = "Caroline",
                            Password = "123456",
                            Phone = "01736-576355",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f6e31308-ecd5-406e-8eed-b5f900b35c8f"),
                            Age = (short)18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "S.Barlow@bing.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Weaver",
                            Name = "Alexis",
                            Password = "123456",
                            Phone = "01357-271383",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ec680d37-3c78-4597-959a-826ccbe5cd75"),
                            Age = (short)63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Thorne@arstechnica.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Peters",
                            Name = "Kimberly",
                            Password = "123456",
                            Phone = "01031-820443",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("760588f8-acaa-4ea9-a375-3ce3d31c5d51"),
                            Age = (short)31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Mann@etsy.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Sanders",
                            Name = "Madison",
                            Password = "123456",
                            Phone = "01341-859839",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d384c4f0-911d-4089-8775-1ecddf07a7de"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Victoria.Sinclair@etsy.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Blair",
                            Name = "Arianna",
                            Password = "123456",
                            Phone = "01519-524345",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0ac7a3d6-cf2b-482f-a96b-875e39b9a45c"),
                            Age = (short)37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Wyatt@lego.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Hilton",
                            Name = "Hunter",
                            Password = "123456",
                            Phone = "01726-286525",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("14b1b425-69bc-4e3b-9018-7be92650b2f9"),
                            Age = (short)62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Dale@yahoo.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lord",
                            Name = "Natalie",
                            Password = "123456",
                            Phone = "01483-384691",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc8732b9-7ebd-464d-b208-bfff84a637c0"),
                            Age = (short)26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Trinity.Abbott@linkedin.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Brown",
                            Name = "Kimberly",
                            Password = "123456",
                            Phone = "01751-055816",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8f9ad609-09fd-4643-9834-0ca71c4174aa"),
                            Age = (short)53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Joyce@msdn.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Haines",
                            Name = "Allison",
                            Password = "123456",
                            Phone = "01700-728115",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9662d609-d92c-4f5c-a357-ed705eb2c697"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Julian.Riddick@etsy.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wyatt",
                            Name = "Alexis",
                            Password = "123456",
                            Phone = "01161-989411",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6e48fa3c-0eda-43ef-987a-2c71737e017a"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "I.Schofield@paypal.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Watson",
                            Name = "Wyatt",
                            Password = "123456",
                            Phone = "01172-373803",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1d982e0b-c407-4808-bdd5-484025b50380"),
                            Age = (short)58,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "T.Burrows@gmail.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Obrien",
                            Name = "Ryder",
                            Password = "123456",
                            Phone = "01783-225243",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("304f9a9f-e998-472d-8e74-a8cf7fa45556"),
                            Age = (short)31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Perkins@arstechnica.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Welch",
                            Name = "Skylar",
                            Password = "123456",
                            Phone = "01175-692716",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22322d41-07c5-4065-acc9-6a78d13ac9db"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Kenny@yelp.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mclean",
                            Name = "Eli",
                            Password = "123456",
                            Phone = "01664-253068",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("56920940-97a4-40a7-8dd6-9b0f5bf2ea65"),
                            Age = (short)42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Williams@bestbuy.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Stuart",
                            Name = "Benjamin",
                            Password = "123456",
                            Phone = "01881-812156",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("387d6984-a33d-4289-b49f-edf16b3c44f0"),
                            Age = (short)46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Scott.Chadwick@deviantart.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mcgregor",
                            Name = "Bailey",
                            Password = "123456",
                            Phone = "01304-463917",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("085b49d1-182f-4fbf-be12-b1996e744096"),
                            Age = (short)53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Evelyn.Bradshaw@ebay.org",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Carroll",
                            Name = "Kayden",
                            Password = "123456",
                            Phone = "01205-050444",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("99a9cd11-a163-441b-9791-e6e531af1380"),
                            Age = (short)57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "N.Lindsay@google.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Chadwick",
                            Name = "David",
                            Password = "123456",
                            Phone = "01218-917725",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f6bee0ca-1a57-409a-8901-b02a92af64b6"),
                            Age = (short)63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Johnson@163.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Watson",
                            Name = "Makayla",
                            Password = "123456",
                            Phone = "01235-792492",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af11174f-81aa-48b8-a523-e7619e51d8c0"),
                            Age = (short)49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X.Schofield@sky.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Weaver",
                            Name = "Ella",
                            Password = "123456",
                            Phone = "01819-051293",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7a9efc08-0245-4519-a5b3-660e30d39d93"),
                            Age = (short)29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Peters@flipkart.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Haines",
                            Name = "Jaxon",
                            Password = "123456",
                            Phone = "01137-792705",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30623352-1a75-4e4a-9856-39966c596a96"),
                            Age = (short)29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cooper.Williams@etsy.org.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thornton",
                            Name = "Robert",
                            Password = "123456",
                            Phone = "01106-142125",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7ec01830-8133-4369-a77f-66272d838fda"),
                            Age = (short)63,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Adam@globo.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Sanders",
                            Name = "Autumn",
                            Password = "123456",
                            Phone = "01918-770597",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("137746de-8bac-44ae-adf6-95b2db56cdf3"),
                            Age = (short)51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Z.Summers@lego.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Osborne",
                            Name = "Cameron",
                            Password = "123456",
                            Phone = "01571-450129",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserAnswer", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "User1")
                        .WithMany("User1Chats")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User2")
                        .WithMany("User2Chats")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "LikedUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("Spark.Core.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("User1Chats");

                    b.Navigation("User2Chats");

                    b.Navigation("UserAnswers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
