// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.DataAccessLayer;

#nullable disable

namespace Spark.DataAccessLayer.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    partial class SparkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tblAnswers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ee7d78d-7dd7-4d7d-8fcb-e8d296694ced"),
                            AnswerText = "Answer 0.1",
                            QuestionId = new Guid("86febca3-d570-4f62-9c3c-30ac7a59e20f")
                        },
                        new
                        {
                            Id = new Guid("4cc139d5-4085-460a-ad9f-e5fec6807aad"),
                            AnswerText = "Answer 0.2",
                            QuestionId = new Guid("86febca3-d570-4f62-9c3c-30ac7a59e20f")
                        },
                        new
                        {
                            Id = new Guid("f8f8828b-6891-40c9-ad40-e18ba9e68f68"),
                            AnswerText = "Answer 0.3",
                            QuestionId = new Guid("86febca3-d570-4f62-9c3c-30ac7a59e20f")
                        },
                        new
                        {
                            Id = new Guid("e92f8d3d-992d-4ea6-a568-9b445b843dd7"),
                            AnswerText = "Answer 0.4",
                            QuestionId = new Guid("86febca3-d570-4f62-9c3c-30ac7a59e20f")
                        },
                        new
                        {
                            Id = new Guid("510a609d-3265-4e27-869e-cff4e1b04375"),
                            AnswerText = "Answer 1.1",
                            QuestionId = new Guid("dce9f771-8f51-4af8-978b-3965db3915f9")
                        },
                        new
                        {
                            Id = new Guid("8441ea01-7beb-47b5-aefe-3dea556518e8"),
                            AnswerText = "Answer 1.2",
                            QuestionId = new Guid("dce9f771-8f51-4af8-978b-3965db3915f9")
                        },
                        new
                        {
                            Id = new Guid("78bcbca8-7642-4327-a104-1d66e5a05cee"),
                            AnswerText = "Answer 1.3",
                            QuestionId = new Guid("dce9f771-8f51-4af8-978b-3965db3915f9")
                        },
                        new
                        {
                            Id = new Guid("1e945f7e-fcf6-4d4a-96bd-d81b11c625f9"),
                            AnswerText = "Answer 1.4",
                            QuestionId = new Guid("dce9f771-8f51-4af8-978b-3965db3915f9")
                        },
                        new
                        {
                            Id = new Guid("4ad04232-616b-48c4-bbed-e2c9d6ea46f8"),
                            AnswerText = "Answer 2.1",
                            QuestionId = new Guid("4312cf57-cd63-4589-a2ea-b5a1a8187b13")
                        },
                        new
                        {
                            Id = new Guid("1b4f9f5f-e156-401c-9c5d-f6fe76c100ae"),
                            AnswerText = "Answer 2.2",
                            QuestionId = new Guid("4312cf57-cd63-4589-a2ea-b5a1a8187b13")
                        },
                        new
                        {
                            Id = new Guid("83010695-7111-496b-beb4-306041bec52e"),
                            AnswerText = "Answer 2.3",
                            QuestionId = new Guid("4312cf57-cd63-4589-a2ea-b5a1a8187b13")
                        },
                        new
                        {
                            Id = new Guid("3707ed54-d2ab-41a6-a991-3163f47e0dd1"),
                            AnswerText = "Answer 2.4",
                            QuestionId = new Guid("4312cf57-cd63-4589-a2ea-b5a1a8187b13")
                        },
                        new
                        {
                            Id = new Guid("d52be4b1-71b8-434f-b3f5-fc8625f74790"),
                            AnswerText = "Answer 3.1",
                            QuestionId = new Guid("20d6e3d8-c6f1-4fc9-8c05-3276007d2f40")
                        },
                        new
                        {
                            Id = new Guid("90498de7-3bb0-4efa-9bef-ad246a530660"),
                            AnswerText = "Answer 3.2",
                            QuestionId = new Guid("20d6e3d8-c6f1-4fc9-8c05-3276007d2f40")
                        },
                        new
                        {
                            Id = new Guid("16f5eb45-7153-4c06-a3f5-b6ba770c8e2c"),
                            AnswerText = "Answer 3.3",
                            QuestionId = new Guid("20d6e3d8-c6f1-4fc9-8c05-3276007d2f40")
                        },
                        new
                        {
                            Id = new Guid("d787233d-b977-44d1-91f4-3a3445307991"),
                            AnswerText = "Answer 3.4",
                            QuestionId = new Guid("20d6e3d8-c6f1-4fc9-8c05-3276007d2f40")
                        },
                        new
                        {
                            Id = new Guid("ebfb590a-90be-4039-84c3-1a8655ef9ec1"),
                            AnswerText = "Answer 4.1",
                            QuestionId = new Guid("ceccd7df-c372-4b49-b070-16bd57ee2456")
                        },
                        new
                        {
                            Id = new Guid("61b3420c-b461-439e-81de-082814549512"),
                            AnswerText = "Answer 4.2",
                            QuestionId = new Guid("ceccd7df-c372-4b49-b070-16bd57ee2456")
                        },
                        new
                        {
                            Id = new Guid("2cc3142a-7a0e-48ae-8844-430d0182f32d"),
                            AnswerText = "Answer 4.3",
                            QuestionId = new Guid("ceccd7df-c372-4b49-b070-16bd57ee2456")
                        },
                        new
                        {
                            Id = new Guid("ded73cc1-a337-435a-b35c-c1be52d58a09"),
                            AnswerText = "Answer 4.4",
                            QuestionId = new Guid("ceccd7df-c372-4b49-b070-16bd57ee2456")
                        },
                        new
                        {
                            Id = new Guid("4f8d098a-8ee8-49f3-b33c-95c5ca976df3"),
                            AnswerText = "Answer 4.5",
                            QuestionId = new Guid("ceccd7df-c372-4b49-b070-16bd57ee2456")
                        },
                        new
                        {
                            Id = new Guid("b8a58d9c-c958-43d8-a17e-e06270c8e198"),
                            AnswerText = "Answer 4.6",
                            QuestionId = new Guid("ceccd7df-c372-4b49-b070-16bd57ee2456")
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("tblChatLog", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("User1Score")
                        .HasColumnType("int");

                    b.Property<int>("User2Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tblLike", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("tblQuestions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("86febca3-d570-4f62-9c3c-30ac7a59e20f"),
                            QuestionBody = "What is your favorite color?"
                        },
                        new
                        {
                            Id = new Guid("dce9f771-8f51-4af8-978b-3965db3915f9"),
                            QuestionBody = "What is your favorite animal?"
                        },
                        new
                        {
                            Id = new Guid("4312cf57-cd63-4589-a2ea-b5a1a8187b13"),
                            QuestionBody = "What is your favorite food?"
                        },
                        new
                        {
                            Id = new Guid("20d6e3d8-c6f1-4fc9-8c05-3276007d2f40"),
                            QuestionBody = "What is your favorite sport?"
                        },
                        new
                        {
                            Id = new Guid("ceccd7df-c372-4b49-b070-16bd57ee2456"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("aa373c94-0f36-41d5-b2f3-57ad38b94a14"),
                            QuestionBody = "What is your favorite book?"
                        },
                        new
                        {
                            Id = new Guid("1ec86833-eeda-43d3-8437-d4ff353864d2"),
                            QuestionBody = "What is your favorite TV show?"
                        },
                        new
                        {
                            Id = new Guid("2c8ea75e-ba92-4590-893f-0dca722c5d8b"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("0a8fe0ca-9dda-4fae-b912-80786d5ce9db"),
                            QuestionBody = "What is your favorite book?"
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasMaxLength(150)
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("861de664-979b-45d8-a340-371111aba2a3"),
                            Age = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@iea.com",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            Latitude = -53.0,
                            Longitude = 58.0,
                            Name = "Admin",
                            Password = "123456",
                            Phone = "05362454497",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e28b5438-8090-4dd1-8677-d38adfeddad9"),
                            Age = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kaangurbuz97@gmail.com",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Gürbüz",
                            Latitude = -51.0,
                            Longitude = 34.0,
                            Name = "Kaan",
                            Password = "123456",
                            Phone = "05394643458",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e42248ef-1924-4882-9775-ad5893ad086e"),
                            Age = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Claire.Little@wikia.us",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Little",
                            Latitude = 25.0,
                            Longitude = 160.0,
                            Name = "Alyssa",
                            Password = "123456",
                            Phone = "01104-099777",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ceb2aaca-e357-4b2b-beb3-4d47f3caec59"),
                            Age = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "E.Lewis@wikipedia.co",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Buckley",
                            Latitude = 13.0,
                            Longitude = -143.0,
                            Name = "Bailey",
                            Password = "123456",
                            Phone = "01347-972894",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9f480b0a-6d42-429b-9961-34270f3e44c9"),
                            Age = 64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Anthony.Schofield@bestbuy.org.uk",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thorne",
                            Latitude = -34.0,
                            Longitude = -164.0,
                            Name = "Andrea",
                            Password = "123456",
                            Phone = "01448-174707",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d0433f54-94c7-4a75-acb0-f4e1c83a4f55"),
                            Age = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Perkins@techcrunch.us",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Smith",
                            Latitude = 65.0,
                            Longitude = 79.0,
                            Name = "Josiah",
                            Password = "123456",
                            Phone = "01534-866454",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7dc57f5f-4c0b-4bc9-9d4a-c3b82c6e5cbd"),
                            Age = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "B.Jennings@expedia.co",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wyatt",
                            Latitude = 77.0,
                            Longitude = 14.0,
                            Name = "Jaxon",
                            Password = "123456",
                            Phone = "01054-573455",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("54491fd5-9cc4-4fe2-9c6f-9b372d0eac88"),
                            Age = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Cassidy@google.net",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Watson",
                            Latitude = -16.0,
                            Longitude = -20.0,
                            Name = "Aiden",
                            Password = "123456",
                            Phone = "01737-350969",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("41e1cb9a-352b-4f6a-aea0-958ff67f8ab6"),
                            Age = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "K.Whittaker@techcrunch.com",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Harris",
                            Latitude = 8.0,
                            Longitude = -143.0,
                            Name = "Cooper",
                            Password = "123456",
                            Phone = "01304-856356",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1673382-a523-4cbe-94f6-776afea46317"),
                            Age = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Andrea.Barlow@gmail.info",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mcfarlane",
                            Latitude = 22.0,
                            Longitude = -145.0,
                            Name = "Brayden",
                            Password = "123456",
                            Phone = "01750-459720",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3d27dbca-f64a-4613-ad62-b454700f397a"),
                            Age = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Mann@yelp.com",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Joyce",
                            Latitude = 13.0,
                            Longitude = 111.0,
                            Name = "Mark",
                            Password = "123456",
                            Phone = "01593-719611",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7a3b59ae-9c37-41d5-a778-5932a72c5c07"),
                            Age = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "F.Akhtar@bing.co.uk",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Seymour",
                            Latitude = 30.0,
                            Longitude = 28.0,
                            Name = "Melanie",
                            Password = "123456",
                            Phone = "01476-764703",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("362b6652-2199-48f4-9df1-cec5acf3ace6"),
                            Age = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Chloe.Stuart@google.co.uk",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Stuart",
                            Latitude = -60.0,
                            Longitude = -92.0,
                            Name = "Caroline",
                            Password = "123456",
                            Phone = "01410-461569",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("47b182aa-2689-43da-9dc4-bdc7c0f2de58"),
                            Age = 51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aiden.Kenny@theguardian.org.uk",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jones",
                            Latitude = -10.0,
                            Longitude = -135.0,
                            Name = "Kaylee",
                            Password = "123456",
                            Phone = "01246-724128",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("87627f52-ecbc-43fd-9c5e-896f14c7901c"),
                            Age = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Austin.Boyd@gmail.co",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Davies",
                            Latitude = 40.0,
                            Longitude = -153.0,
                            Name = "Genesis",
                            Password = "123456",
                            Phone = "01516-617191",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2daf931e-0568-4ecd-a112-c7b6cc08cd52"),
                            Age = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Oliver.Wyatt@amazon.biz",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Savage",
                            Latitude = 57.0,
                            Longitude = 38.0,
                            Name = "Sofia",
                            Password = "123456",
                            Phone = "01192-574386",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7dd654a3-efc2-4241-9363-63f2d59ffa84"),
                            Age = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Watson@lego.org",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "White",
                            Latitude = 48.0,
                            Longitude = 131.0,
                            Name = "Gabriel",
                            Password = "123456",
                            Phone = "01728-145816",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b567d950-0a9e-4d7d-a708-48c1857d149a"),
                            Age = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "E.Wyatt@qq.org.uk",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Joyce",
                            Latitude = 37.0,
                            Longitude = -160.0,
                            Name = "Gabriella",
                            Password = "123456",
                            Phone = "01185-085486",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("563bdc59-adad-4182-9ce0-0822f3de5447"),
                            Age = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Natalie.Thomas@cnn.com",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Welch",
                            Latitude = 70.0,
                            Longitude = -156.0,
                            Name = "Addison",
                            Password = "123456",
                            Phone = "01413-125869",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("557b96f3-763f-41d9-8ca2-1996d5d011c3"),
                            Age = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "J.Nash@ebay.net",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Johnson",
                            Latitude = -17.0,
                            Longitude = -86.0,
                            Name = "Nolan",
                            Password = "123456",
                            Phone = "01000-056460",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("85774bde-7d0b-4a10-85dd-a5f8ca7a156c"),
                            Age = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Elijah.Silva@baidu.org.uk",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Giles",
                            Latitude = -13.0,
                            Longitude = -8.0,
                            Name = "Samantha",
                            Password = "123456",
                            Phone = "01843-227178",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a60419d9-f0e1-4386-8475-681d5982c7ec"),
                            Age = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Wilson@stackoverflow.co.uk",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Hilton",
                            Latitude = -68.0,
                            Longitude = 50.0,
                            Name = "Tyler",
                            Password = "123456",
                            Phone = "01029-729394",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0ede5275-71db-4950-8d1b-f973cb30991a"),
                            Age = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Natalie.Burrows@deviantart.biz",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Vaughan",
                            Latitude = 43.0,
                            Longitude = 40.0,
                            Name = "Samuel",
                            Password = "123456",
                            Phone = "01324-795038",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("60516aab-b786-485e-b82f-75241b800233"),
                            Age = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "K.Boyd@arstechnica.com",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mcfarlane",
                            Latitude = -57.0,
                            Longitude = 149.0,
                            Name = "Tyler",
                            Password = "123456",
                            Phone = "01187-730565",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22cb8eca-c1c8-4182-932a-8b91705aaa40"),
                            Age = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Mohamed@pinterest.com",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Obrien",
                            Latitude = -27.0,
                            Longitude = 96.0,
                            Name = "Aaliyah",
                            Password = "123456",
                            Phone = "01734-013161",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f3532fc1-9890-4d88-accb-6dae646a2e7b"),
                            Age = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kennedy.Sanders@wikipedia.co.uk",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lewis",
                            Latitude = -87.0,
                            Longitude = -19.0,
                            Name = "Charlotte",
                            Password = "123456",
                            Phone = "01855-398153",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8494b896-eadc-49ec-8299-0208ba3e0e81"),
                            Age = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Sanders@taobao.co",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Sanders",
                            Latitude = -15.0,
                            Longitude = -130.0,
                            Name = "Jose",
                            Password = "123456",
                            Phone = "01078-555176",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("de1b6fd9-a28b-42fb-ac09-8affe3bb93d9"),
                            Age = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aria.Taylor@gmail.org.uk",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jennings",
                            Latitude = -84.0,
                            Longitude = 22.0,
                            Name = "Colton",
                            Password = "123456",
                            Phone = "01259-209926",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e2c8de87-08cf-4c01-80f8-62360288ed28"),
                            Age = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Grace.Smith@linkedin.biz",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Haines",
                            Latitude = -63.0,
                            Longitude = -112.0,
                            Name = "Mackenzie",
                            Password = "123456",
                            Phone = "01151-149218",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9641c489-8d13-4be5-9551-b32aca324e16"),
                            Age = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "D.Mcfarlane@expedia.us",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Rossi",
                            Latitude = 42.0,
                            Longitude = -99.0,
                            Name = "Autumn",
                            Password = "123456",
                            Phone = "01090-340981",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5efb0982-cf7c-458d-9439-c5b72f68aaf8"),
                            Age = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nolan.Savage@theguardian.info",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thorne",
                            Latitude = -40.0,
                            Longitude = 98.0,
                            Name = "Christian",
                            Password = "123456",
                            Phone = "01189-439870",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1a5da2c-fbfe-44a4-b9a3-b6bbb6c5b6c7"),
                            Age = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Wyatt@arstechnica.org",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Kenny",
                            Latitude = 31.0,
                            Longitude = 127.0,
                            Name = "Isaac",
                            Password = "123456",
                            Phone = "01285-495162",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("31077c93-3fcd-4512-85e2-1c2fed1a843a"),
                            Age = 56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kennedy.Naylor@yahoo.co",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Barlow",
                            Latitude = -6.0,
                            Longitude = 142.0,
                            Name = "Alexander",
                            Password = "123456",
                            Phone = "01635-224884",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5b2a7808-a368-489a-9743-4f152cd00e58"),
                            Age = 52,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Watson@globo.org.uk",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jackson",
                            Latitude = -62.0,
                            Longitude = 113.0,
                            Name = "Michael",
                            Password = "123456",
                            Phone = "01566-965707",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("832e24ca-737f-4135-84ce-b6b936723154"),
                            Age = 57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Julian.Coles@globo.com",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "White",
                            Latitude = -39.0,
                            Longitude = 108.0,
                            Name = "Kayla",
                            Password = "123456",
                            Phone = "01279-807862",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8bdb3d0e-2a6f-4e32-8a81-b6cab0beefe8"),
                            Age = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "H.Leach@ebay.net",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Summers",
                            Latitude = -70.0,
                            Longitude = 7.0,
                            Name = "Brianna",
                            Password = "123456",
                            Phone = "01373-153828",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ea5ccd44-a0e1-4006-bccb-8eec6f70b44e"),
                            Age = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Henry.Swift@ask.co",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Lindsay",
                            Latitude = -76.0,
                            Longitude = -104.0,
                            Name = "Cameron",
                            Password = "123456",
                            Phone = "01679-898758",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b7987c9-9b20-4033-9977-38f7b9df6f56"),
                            Age = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Evans@amazon.info",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "White",
                            Latitude = -79.0,
                            Longitude = 1.0,
                            Name = "Bentley",
                            Password = "123456",
                            Phone = "01480-007765",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1d00bfe7-8f02-4db0-823b-ff8de9c589be"),
                            Age = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alexandra.Wood@lego.co.uk",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mclean",
                            Latitude = 50.0,
                            Longitude = 71.0,
                            Name = "Alex",
                            Password = "123456",
                            Phone = "01631-840112",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e79caf95-7982-4cc6-9899-7376bf4295f3"),
                            Age = 61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dominic.Savage@baidu.co",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Carroll",
                            Latitude = 76.0,
                            Longitude = 130.0,
                            Name = "Layla",
                            Password = "123456",
                            Phone = "01587-353209",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7725503b-1da6-497a-94f0-b2e5c6ca2396"),
                            Age = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Gabriel.Peters@msdn.co.uk",
                            Gender = "Man",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mcgrath",
                            Latitude = 30.0,
                            Longitude = -20.0,
                            Name = "Isabella",
                            Password = "123456",
                            Phone = "01384-554331",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4692f8b5-6883-4fde-9788-4a2e81c49136"),
                            Age = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "O.Harris@amazon.net",
                            Gender = "Woman",
                            ImagePath = "user",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Cassidy",
                            Latitude = -43.0,
                            Longitude = 174.0,
                            Name = "Kaylee",
                            Password = "123456",
                            Phone = "01793-000005",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserAnswer", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "User1")
                        .WithMany("User1Chats")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User2")
                        .WithMany("User2Chats")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "LikedUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("Spark.Core.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("User1Chats");

                    b.Navigation("User2Chats");

                    b.Navigation("UserAnswers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
