// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.DataAccessLayer;

#nullable disable

namespace Spark.DataAccessLayer.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    partial class SparkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("tblAnswers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e04e89a-1de6-4bb8-aa38-6d8d06737c11"),
                            AnswerText = "Answer 0.1",
                            QuestionId = new Guid("ddacb0ba-edd4-403a-a943-142d59839459")
                        },
                        new
                        {
                            Id = new Guid("09a54ed7-35a4-4609-9588-757980e2aa8a"),
                            AnswerText = "Answer 0.2",
                            QuestionId = new Guid("ddacb0ba-edd4-403a-a943-142d59839459")
                        },
                        new
                        {
                            Id = new Guid("a06db825-2dbd-4d9d-b14d-0fba808e356b"),
                            AnswerText = "Answer 0.3",
                            QuestionId = new Guid("ddacb0ba-edd4-403a-a943-142d59839459")
                        },
                        new
                        {
                            Id = new Guid("4ad5809a-8923-432d-9165-41e9b01ca23b"),
                            AnswerText = "Answer 0.4",
                            QuestionId = new Guid("ddacb0ba-edd4-403a-a943-142d59839459")
                        },
                        new
                        {
                            Id = new Guid("44aebeae-4ee2-4148-880b-64411d567b16"),
                            AnswerText = "Answer 1.1",
                            QuestionId = new Guid("f5b6fb3f-64d5-4b24-b6ec-b85c1c628c6d")
                        },
                        new
                        {
                            Id = new Guid("679796f0-5816-48a5-96d7-c4f42f875d62"),
                            AnswerText = "Answer 1.2",
                            QuestionId = new Guid("f5b6fb3f-64d5-4b24-b6ec-b85c1c628c6d")
                        },
                        new
                        {
                            Id = new Guid("fcd4fad0-2081-4f30-8034-c467f653aff2"),
                            AnswerText = "Answer 1.3",
                            QuestionId = new Guid("f5b6fb3f-64d5-4b24-b6ec-b85c1c628c6d")
                        },
                        new
                        {
                            Id = new Guid("4e403cc0-d4ce-4bdf-9403-d76774914c67"),
                            AnswerText = "Answer 1.4",
                            QuestionId = new Guid("f5b6fb3f-64d5-4b24-b6ec-b85c1c628c6d")
                        },
                        new
                        {
                            Id = new Guid("adf4d301-912c-4582-b421-e8748b9cc3ba"),
                            AnswerText = "Answer 2.1",
                            QuestionId = new Guid("126320f6-6439-4bd8-8a2f-58a57fef4a5e")
                        },
                        new
                        {
                            Id = new Guid("45d9ff96-467d-4c4f-b654-388b4add16a2"),
                            AnswerText = "Answer 2.2",
                            QuestionId = new Guid("126320f6-6439-4bd8-8a2f-58a57fef4a5e")
                        },
                        new
                        {
                            Id = new Guid("31baeca1-f51e-4282-9e62-3ae5e719e90b"),
                            AnswerText = "Answer 2.3",
                            QuestionId = new Guid("126320f6-6439-4bd8-8a2f-58a57fef4a5e")
                        },
                        new
                        {
                            Id = new Guid("c40a7f94-c432-4c4f-b411-e4b4ac18522e"),
                            AnswerText = "Answer 2.4",
                            QuestionId = new Guid("126320f6-6439-4bd8-8a2f-58a57fef4a5e")
                        },
                        new
                        {
                            Id = new Guid("3fc32342-f2ab-42e8-8064-01e5dda8ca76"),
                            AnswerText = "Answer 3.1",
                            QuestionId = new Guid("9b1c28fa-31d4-4412-867d-a594050f8c7a")
                        },
                        new
                        {
                            Id = new Guid("1b7c312a-3cc0-4143-b794-b78a1e6c41b4"),
                            AnswerText = "Answer 3.2",
                            QuestionId = new Guid("9b1c28fa-31d4-4412-867d-a594050f8c7a")
                        },
                        new
                        {
                            Id = new Guid("077d4006-dfd0-4a4b-9161-1e656aebc215"),
                            AnswerText = "Answer 3.3",
                            QuestionId = new Guid("9b1c28fa-31d4-4412-867d-a594050f8c7a")
                        },
                        new
                        {
                            Id = new Guid("71ba581a-06dd-4f6a-9368-5af97bc91a49"),
                            AnswerText = "Answer 3.4",
                            QuestionId = new Guid("9b1c28fa-31d4-4412-867d-a594050f8c7a")
                        },
                        new
                        {
                            Id = new Guid("0a1af1a4-405c-4fd8-83d5-e3c48c1d18e6"),
                            AnswerText = "Answer 4.1",
                            QuestionId = new Guid("2953a69c-dde5-47ec-98da-4cdb2e6b2922")
                        },
                        new
                        {
                            Id = new Guid("28f09c1a-40dc-4fe1-b876-2b49e906336d"),
                            AnswerText = "Answer 4.2",
                            QuestionId = new Guid("2953a69c-dde5-47ec-98da-4cdb2e6b2922")
                        },
                        new
                        {
                            Id = new Guid("526af9d9-bcf2-4405-abf0-53f7397d5943"),
                            AnswerText = "Answer 4.3",
                            QuestionId = new Guid("2953a69c-dde5-47ec-98da-4cdb2e6b2922")
                        },
                        new
                        {
                            Id = new Guid("20bb699e-6bec-44ae-abb7-bc700bf2301d"),
                            AnswerText = "Answer 4.4",
                            QuestionId = new Guid("2953a69c-dde5-47ec-98da-4cdb2e6b2922")
                        },
                        new
                        {
                            Id = new Guid("3f42ae72-c3b6-4898-b832-c4e072439ae9"),
                            AnswerText = "Answer 4.5",
                            QuestionId = new Guid("2953a69c-dde5-47ec-98da-4cdb2e6b2922")
                        },
                        new
                        {
                            Id = new Guid("8b1fcc1a-5de8-48f8-82a7-44140ea66b66"),
                            AnswerText = "Answer 4.6",
                            QuestionId = new Guid("2953a69c-dde5-47ec-98da-4cdb2e6b2922")
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("tblChatLog", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("User1Score")
                        .HasColumnType("int");

                    b.Property<int>("User2Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LikedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tblLike", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("tblQuestions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ddacb0ba-edd4-403a-a943-142d59839459"),
                            QuestionBody = "What is your favorite color?"
                        },
                        new
                        {
                            Id = new Guid("f5b6fb3f-64d5-4b24-b6ec-b85c1c628c6d"),
                            QuestionBody = "What is your favorite animal?"
                        },
                        new
                        {
                            Id = new Guid("126320f6-6439-4bd8-8a2f-58a57fef4a5e"),
                            QuestionBody = "What is your favorite food?"
                        },
                        new
                        {
                            Id = new Guid("9b1c28fa-31d4-4412-867d-a594050f8c7a"),
                            QuestionBody = "What is your favorite sport?"
                        },
                        new
                        {
                            Id = new Guid("2953a69c-dde5-47ec-98da-4cdb2e6b2922"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("5ec93cce-92c8-4f6d-96e1-6c4bf4a5d915"),
                            QuestionBody = "What is your favorite book?"
                        },
                        new
                        {
                            Id = new Guid("3250d019-b02b-4dce-9cf0-521c587ac6e2"),
                            QuestionBody = "What is your favorite TV show?"
                        },
                        new
                        {
                            Id = new Guid("24fa12ad-1eb2-4c54-8a77-fa8a439fa7bb"),
                            QuestionBody = "What is your favorite movie?"
                        },
                        new
                        {
                            Id = new Guid("5cbb639d-0571-41df-ad92-5d3be6212969"),
                            QuestionBody = "What is your favorite book?"
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Age")
                        .HasMaxLength(150)
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1a4ceaa-285b-443a-80b8-166e47e71adf"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@iea.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            Latitude = -15.0,
                            Longitude = -63.0,
                            Name = "Admin",
                            Password = "123456",
                            Phone = "05362454497",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1e456020-62ec-4f39-86aa-6b9c5c039298"),
                            Age = (short)25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kaangurbuz97@gmail.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "Gürbüz",
                            Latitude = 37.0,
                            Longitude = 9.0,
                            Name = "Kaan",
                            Password = "123456",
                            Phone = "05394643458",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b98484a-355c-456b-9be3-d0c2f2b6b631"),
                            Age = (short)57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Amelia.Wood@wordpress.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mac",
                            Latitude = 43.0,
                            Longitude = -177.0,
                            Name = "Cooper",
                            Password = "123456",
                            Phone = "01490-278169",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("edfc8a0e-759b-403f-8762-428ddb9500de"),
                            Age = (short)56,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jason.Walters@techcrunch.us",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Stuart",
                            Latitude = -37.0,
                            Longitude = -17.0,
                            Name = "Mark",
                            Password = "123456",
                            Phone = "01346-272290",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cca2117d-4a03-4595-af30-2dd3b695f0fc"),
                            Age = (short)33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mark.Mcfarlane@wikia.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wood",
                            Latitude = -29.0,
                            Longitude = 89.0,
                            Name = "Austin",
                            Password = "123456",
                            Phone = "01389-237179",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c79d2216-6edb-43e8-83bf-bba091d64581"),
                            Age = (short)47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Cassidy@microsoft.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Adam",
                            Latitude = -66.0,
                            Longitude = 106.0,
                            Name = "London",
                            Password = "123456",
                            Phone = "01586-516874",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("61f6bc31-740d-4097-8245-5e07b2bbb1f5"),
                            Age = (short)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Faith.Baldwin@yahoo.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jackson",
                            Latitude = -51.0,
                            Longitude = 60.0,
                            Name = "Aaliyah",
                            Password = "123456",
                            Phone = "01570-017370",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8933c4ec-8823-4a6f-b930-c85e4055563c"),
                            Age = (short)24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Taylor.Mellor@theguardian.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mann",
                            Latitude = 69.0,
                            Longitude = -49.0,
                            Name = "Scarlett",
                            Password = "123456",
                            Phone = "01724-299440",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("57ae6816-06d6-4c5a-9698-c1c09a4d0248"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Mann@flipkart.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jones",
                            Latitude = -23.0,
                            Longitude = -84.0,
                            Name = "Isaiah",
                            Password = "123456",
                            Phone = "01413-333627",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0e4c0246-1d07-40a4-82a6-9607ec62d53f"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ryan.Williams@microsoft.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Shepherd",
                            Latitude = -21.0,
                            Longitude = -79.0,
                            Name = "Katherine",
                            Password = "123456",
                            Phone = "01489-186933",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2e1e9296-5d37-4acc-bf8e-e5a6c6256936"),
                            Age = (short)35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "S.Hilton@ask.info",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Carroll",
                            Latitude = 49.0,
                            Longitude = -79.0,
                            Name = "Violet",
                            Password = "123456",
                            Phone = "01972-345987",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ca080383-548f-4208-90b1-9c7fb7019ccc"),
                            Age = (short)28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Lewis@arstechnica.com",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Coles",
                            Latitude = 33.0,
                            Longitude = -50.0,
                            Name = "Skylar",
                            Password = "123456",
                            Phone = "01777-326182",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("89bf02a3-4a58-49c4-b34e-6bb16d606ac6"),
                            Age = (short)35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hailey.Lord@youtube.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jackson",
                            Latitude = -52.0,
                            Longitude = -3.0,
                            Name = "Lily",
                            Password = "123456",
                            Phone = "01251-650416",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4ca7081b-17b8-4b7f-b0b6-3d96ef7b1c2f"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Angel.Cassidy@lego.org",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Whittaker",
                            Latitude = -4.0,
                            Longitude = -162.0,
                            Name = "Aiden",
                            Password = "123456",
                            Phone = "01255-941309",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("07a07261-67f0-4b6a-9dcd-197f07fe950f"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "T.Johnson@gmail.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Silva",
                            Latitude = -51.0,
                            Longitude = -75.0,
                            Name = "Mia",
                            Password = "123456",
                            Phone = "01978-492178",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e5de8bf3-901b-41fe-a4c4-479d2c6536aa"),
                            Age = (short)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "C.Watson@qq.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Mclean",
                            Latitude = -23.0,
                            Longitude = -130.0,
                            Name = "London",
                            Password = "123456",
                            Phone = "01228-773046",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("15d29786-3875-4260-9307-8b128be0d748"),
                            Age = (short)57,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Davies@msdn.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Blair",
                            Latitude = 20.0,
                            Longitude = -103.0,
                            Name = "Nathan",
                            Password = "123456",
                            Phone = "01018-106319",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("97d32340-4568-4717-8687-a5336dc032b2"),
                            Age = (short)23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "A.Adam@stackoverflow.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Blair",
                            Latitude = -25.0,
                            Longitude = -180.0,
                            Name = "Christopher",
                            Password = "123456",
                            Phone = "01186-376802",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ae380d63-57ef-481b-a745-1156ded16ee8"),
                            Age = (short)34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Molly.Johnson@bing.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Dale",
                            Latitude = -56.0,
                            Longitude = 83.0,
                            Name = "Hudson",
                            Password = "123456",
                            Phone = "01544-642303",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("086210dd-4823-426a-99e2-6267ce023cb3"),
                            Age = (short)31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Luke.Stuart@live.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Seymour",
                            Latitude = -83.0,
                            Longitude = 156.0,
                            Name = "Claire",
                            Password = "123456",
                            Phone = "01913-986952",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f540c535-a928-4a49-8845-50491e29273d"),
                            Age = (short)38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lily.Perkins@bet365.co.uk",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Power",
                            Latitude = -67.0,
                            Longitude = 149.0,
                            Name = "Xavier",
                            Password = "123456",
                            Phone = "01767-212541",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30943e7e-9e85-4066-9c22-5df11e872c2e"),
                            Age = (short)49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Reagan.Adam@studio1337.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thorne",
                            Latitude = -8.0,
                            Longitude = -144.0,
                            Name = "Nathaniel",
                            Password = "123456",
                            Phone = "01113-350733",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0d01e268-e569-4953-b4c9-cdea823abea0"),
                            Age = (short)64,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Z.Taylor@globo.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Walters",
                            Latitude = 44.0,
                            Longitude = 126.0,
                            Name = "Audrey",
                            Password = "123456",
                            Phone = "01920-774571",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a4bcac39-5d90-4f95-ab1d-3ec1471ddc17"),
                            Age = (short)20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "N.Akhtar@sky.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Whitehouse",
                            Latitude = 82.0,
                            Longitude = 52.0,
                            Name = "Brooklyn",
                            Password = "123456",
                            Phone = "01093-377486",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("08762458-9b5b-4924-90ce-26154de5b4e8"),
                            Age = (short)33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nicholas.Obrien@linkedin.us",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Harris",
                            Latitude = -67.0,
                            Longitude = -57.0,
                            Name = "Blake",
                            Password = "123456",
                            Phone = "01229-577866",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("17a0f5cf-d430-4ae3-8cb3-76c4ca48c022"),
                            Age = (short)45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Andrew.Cullen@qq.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Sanders",
                            Latitude = -47.0,
                            Longitude = 153.0,
                            Name = "Serenity",
                            Password = "123456",
                            Phone = "01393-064542",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1a99fe07-dd8b-4773-8974-2a2fe5d60cb4"),
                            Age = (short)62,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aaron.Thompson@deviantart.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Evans",
                            Latitude = -11.0,
                            Longitude = -20.0,
                            Name = "Brody",
                            Password = "123456",
                            Phone = "01592-815954",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b13ae2ca-9444-4574-b977-98d5601083c5"),
                            Age = (short)21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nicholas.Brown@sohu.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Thomas",
                            Latitude = -5.0,
                            Longitude = 175.0,
                            Name = "Dylan",
                            Password = "123456",
                            Phone = "01122-447518",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d9239f67-7f7b-4eb7-aaba-e02f96f9c33a"),
                            Age = (short)53,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Taylor@taobao.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Osborne",
                            Latitude = 45.0,
                            Longitude = -83.0,
                            Name = "Kylie",
                            Password = "123456",
                            Phone = "01108-910901",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ce0cc5ff-3398-449b-80d3-a7b3fce671ae"),
                            Age = (short)47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "M.Whelan@ask.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Little",
                            Latitude = -27.0,
                            Longitude = 107.0,
                            Name = "Kevin",
                            Password = "123456",
                            Phone = "01799-894999",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("93c705c6-0a7a-4fca-b5b8-b01bb84308e3"),
                            Age = (short)29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "L.Boyd@globo.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Shepherd",
                            Latitude = 8.0,
                            Longitude = 111.0,
                            Name = "Addison",
                            Password = "123456",
                            Phone = "01109-635858",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a8a0e290-413f-4d7e-9ecd-c335d9eab7db"),
                            Age = (short)59,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Luke.Johnson@baidu.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Roberts",
                            Latitude = 56.0,
                            Longitude = -165.0,
                            Name = "Charlotte",
                            Password = "123456",
                            Phone = "01558-826457",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5179948b-9637-4487-b53c-c7628ce643e4"),
                            Age = (short)35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Isaac.Silva@google.net",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Evans",
                            Latitude = 65.0,
                            Longitude = 11.0,
                            Name = "Christian",
                            Password = "123456",
                            Phone = "01641-247555",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3d372677-8ab2-4a15-bcef-af8dbc28ce13"),
                            Age = (short)36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kevin.Swift@flipkart.info",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Watson",
                            Latitude = -85.0,
                            Longitude = 11.0,
                            Name = "Genesis",
                            Password = "123456",
                            Phone = "01396-607291",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a536ac6a-6deb-4ed7-8182-b7e15c7fdf5d"),
                            Age = (short)51,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "G.Mac@etsy.com",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Wilson",
                            Latitude = 84.0,
                            Longitude = 141.0,
                            Name = "John",
                            Password = "123456",
                            Phone = "01032-567049",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0c3ee6cc-f34e-4d7c-b3f6-ea02e281cc64"),
                            Age = (short)36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Caleb.Whelan@deviantart.co",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Jennings",
                            Latitude = 42.0,
                            Longitude = 174.0,
                            Name = "Ellie",
                            Password = "123456",
                            Phone = "01602-487479",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6dc186bb-e8dc-492b-9bbd-3a73a3839f80"),
                            Age = (short)61,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "P.Wright@live.co",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Briggs",
                            Latitude = 24.0,
                            Longitude = 84.0,
                            Name = "Maya",
                            Password = "123456",
                            Phone = "01471-552066",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eebc7316-1071-4120-b807-7904ed509407"),
                            Age = (short)27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Julian.Thompson@etsy.net",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Stuart",
                            Latitude = -40.0,
                            Longitude = -119.0,
                            Name = "Josiah",
                            Password = "123456",
                            Phone = "01713-578441",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("50ff8cf8-25df-4ad2-9281-6d5841c12dcb"),
                            Age = (short)60,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "S.Mann@linkedin.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Chadwick",
                            Latitude = -84.0,
                            Longitude = -38.0,
                            Name = "Matthew",
                            Password = "123456",
                            Phone = "01301-306119",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3d9b4001-cf97-4bdc-94e7-888c8c650a52"),
                            Age = (short)19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bailey.Riddick@maplin.co.uk",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Kenny",
                            Latitude = -20.0,
                            Longitude = -150.0,
                            Name = "Adrian",
                            Password = "123456",
                            Phone = "01799-887597",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7c9cc5b2-19aa-4b68-ac1c-c550600cf043"),
                            Age = (short)39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Paul.Peters@bestbuy.biz",
                            Gender = "Man",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Boyd",
                            Latitude = 26.0,
                            Longitude = 139.0,
                            Name = "Carter",
                            Password = "123456",
                            Phone = "01747-186093",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ea07bbb3-e75d-4369-93b5-07267fa42ded"),
                            Age = (short)54,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "K.Kenny@sohu.biz",
                            Gender = "Woman",
                            IsActive = true,
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Stuart",
                            Latitude = 69.0,
                            Longitude = 8.0,
                            Name = "Anthony",
                            Password = "123456",
                            Phone = "01588-681737",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserAnswer", (string)null);
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Spark.Core.Models.Chat", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "User1")
                        .WithMany("User1Chats")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User2")
                        .WithMany("User2Chats")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Spark.Core.Models.Like", b =>
                {
                    b.HasOne("Spark.Core.Models.User", "LikedUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("Spark.Core.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spark.Core.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spark.Core.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Spark.Core.Models.User", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("User1Chats");

                    b.Navigation("User2Chats");

                    b.Navigation("UserAnswers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
